*-----------------------------------------------------------------------------
* <Rating>-7</Rating>
*-----------------------------------------------------------------------------
SUBROUTINE L.APAP.RTE.CUST.AND.DATE.TXN(Y.FINAL)
$INSERT T24.BP I_COMMON
$INSERT T24.BP I_EQUATE
$INSERT T24.BP I_ENQUIRY.COMMON
$INSERT LAPAP.BP I_F.REDO.RTE.CUST.CASHTXN

*OBJECTOS PARA ABRIR EL ARCHIVO REDO.RTE.CUST.CASHTXN
FN.TABLE = "F.REDO.RTE.CUST.CASHTXN"
FT.RTE = ""
RS.RTE = ""
ERR.RTE = ""
Y.POS = ""
Y.HIS.SUF = ""

*PARA EJECUTAR QUERY
SEL.LIST = ""
NO.OF.REC = ""
SEL.ERR = ""

*OBTENEMOS LOS CAMPOS ENVIADOS DESDE EL SS
LOCATE "CUST.ID" IN D.FIELDS<1> SETTING CUS.POS THEN
CUST.ID = D.RANGE.AND.VALUE<CUS.POS>
END

LOCATE "DATE.FROM" IN D.FIELDS<1> SETTING CUS.POS THEN
DATE.FROM = D.RANGE.AND.VALUE<CUS.POS>
END
*FIN

*PARA ABRIR EL ACHIVO DE REDO.RTE.CUST.CASHTXN
CALL OPF(FN.TABLE, FT.RTE)

* FORMAMOS EL QUERY A EJECUTAR
SEL.CMD = "SELECT " : FN.TABLE : " WITH @ID LIKE ..." : CUST.ID : "." : DATE.FROM : "..."

* EGECUTAMOS LA CONSULTA A LA TABLA DE REDO.RTE.CUST.CASHTXN
CALL EB.READLIST(SEL.CMD, SEL.LIST,"", NO.OF.REC, SEL.ERR)

LOOP
REMOVE Y.RTE.ID FROM SEL.LIST SETTING RTE.POS

WHILE Y.RTE.ID DO

CALL F.READ(FN.TABLE, Y.RTE.ID, RS.RTE, FT.RTE, ERR.RTE)

*CAMPOR A RETORNAR
VAL.NO1 = Y.RTE.ID
VAL.NO2 = "|" : RS.RTE<RTE.INITIAL.ID>
VAL.NO3 = "|" : RS.RTE<RTE.TXN.ID>
VAL.NO4 = "|" : RS.RTE<RTE.BRANCH.CODE>
VAL.NO5 = ""

IF RS.RTE<RTE.CASH.AMOUNT> = '' THEN
VAL.NO5 = "|0"

END ELSE
VAL.NO5 = "|" : RS.RTE<RTE.CASH.AMOUNT>
END

Y.FINAL<-1> = VAL.NO1 : VAL.NO2 : VAL.NO3 : VAL.NO4 : VAL.NO5

REPEAT

END
