*-----------------------------------------------------------------------------
* <Rating>-51</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE L.APAP.VAL.LCO.AC.CAT.RT
    $INSERT T24.BP I_COMMON
    $INSERT T24.BP I_EQUATE
    $INSERT T24.BP I_F.ACCOUNT
    $INSERT TAM.BP I_F.LATAM.CARD.ORDER
    $INSERT TAM.BP I_F.LATAM.CARD.CUSTOMER
*$INSERT BP I_F.ST.L.APAP.TD.CAT.RES

    GOSUB INI
    GOSUB PROCESS
INI:
    Y.ACCOUNT.NUMBER = COMI   ;*R.NEW(CARD.IS.ACCOUNT) SI ES INPUT ROUTINE

    FN.ACC = "FBNK.ACCOUNT"
    F.ACC = ""
    CALL OPF(FN.ACC,F.ACC)
    
    FN.LCC = "F.LATAM.CARD.CUSTOMER"
    F.LCC = ""
    CALL OPF(FN.LCC,F.LCC)
    
    FN.LCO = "F.LATAM.CARD.ORDER"
    F.LCO = ""
    CALL OPF(FN.LCO,F.LCO)

    FN.CAT.RES = "FBNK.ST.L.APAP.TD.CAT.RES"
    F.CAT.RES = ""
    CALL OPF(FN.CAT.RES,F.CAT.RES)
    
    RETURN

PROCESS:
    GOSUB READ.CAT.RESTRICT
    GOSUB READ.ACCOUNT
    GOSUB CONSULTA.CUENTA
   
    Y.ACC.CATEGORY = R.ACC<AC.CATEGORY>
    Y.RES.CATEGORY = R.CAT.RES<1>       ;*ST.TDCR.ACC.CATEGORY
    FINDSTR Y.ACC.CATEGORY IN Y.RES.CATEGORY SETTING Ap, Vp THEN
        MESSAGE = "T.D. NO PUEDE SER RELACIONADA A CUENTA DE LA CATEGORIA ":Y.ACC.CATEGORY
        E = MESSAGE
        ETEXT = E
        CALL ERR
    END
    RETURN

READ.ACCOUNT:
    R.ACC = ''; ACC.ERROR = '';
    CALL F.READ(FN.ACC,Y.ACCOUNT.NUMBER,R.ACC,F.ACC,ACC.ERROR)
     Y.COD.CLIENTE  = R.ACC<AC.CUSTOMER>
    RETURN

READ.CAT.RESTRICT:
    R.CAT.RES = ''; CAT.RES.ERROR = '';
    CALL F.READ(FN.CAT.RES,'SYSTEM',R.CAT.RES,F.CAT.RES,CAT.RES.ERROR)
    RETURN

CONSULTA.CUENTA:
  Y.TIENE.TARJETA = 'false'

  CALL F.READ(FN.LCC,Y.COD.CLIENTE,R.LATAM.CUSTOMER,F.LCC,ERROR.LATAM.CUSTOMER)
  Y.ACCS.CUSTOMER = R.LATAM.CUSTOMER<APAP.DC.ACCOUNT.NO>
  Y.CARDS = R.LATAM.CUSTOMER<APAP.DC.CARD.NO>
  Y.CANT.ACC = DCOUNT(Y.ACCS.CUSTOMER,@VM)

  FOR CONT=1 TO Y.CANT.ACC STEP 1

   IF (Y.ACCS.CUSTOMER<1,CONT> = Y.ACCOUNT.NUMBER) THEN 
      LATAM.NO = Y.CARDS<1,CONT>
      
      CALL F.READ(FN.LCO,LATAM.NO,R.LATAM.ORDER,F.LCO,ERROR.LATAM)
      Y.CARD.STATUS = R.LATAM.ORDER<CARD.IS.CARD.STATUS>
  
      IF (Y.CARD.STATUS EQ 90 OR Y.CARD.STATUS EQ 94 OR Y.CARD.STATUS EQ 75 OR Y.CARD.STATUS EQ 74) THEN 
          Y.TIENE.TARJETA = 'true'
      END 
   END 

  NEXT CONT

   IF (Y.COD.CLIENTE NE "" AND Y.TIENE.TARJETA EQ 'true' ) THEN 
       R.NEW(CARD.IS.TYPE.OF.CARD)  = "ADICIONAL"
       R.NEW(CARD.IS.PROSPECT.ID) = Y.COD.CLIENTE
   END 

RETURN 

END
