*-----------------------------------------------------------------------------
* <Rating>-54</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE LAPAP.REPORTE.ASAMBLEA.RT(Y.FINAL)
    $INSERT T24.BP I_COMMON
    $INSERT T24.BP I_EQUATE
    $INSERT T24.BP I_ENQUIRY.COMMON
    $INSERT T24.BP I_F.DATES
    $INSERT BP I_F.ST.L.APAP.ASAMBLEA.PARTIC
    $INSERT BP I_F.ST.L.APAP.ASAMBLEA.PARAM

    GOSUB CARGADOR
    GOSUB DETALLES
    GOSUB FINAL

CARGADOR:
    FN.PA = "FBNK.ST.L.APAP.ASAMBLEA.PARTIC"
    FV.PA = ""
    R.PA = ""
    PA.ERR = ""
    CALL OPF(FN.PA,FV.PA)

    FN.PARAM = "FBNK.ST.L.APAP.ASAMBLEA.PARAM"
    FV.PARAM = ""
    R.PARAM = ""
    PARAM.ERR = ""
    CALL OPF(FN.PARAM,FV.PARAM)

    FN.REP = "F.L.APAP.REPORTE.ASAMBLEA.T1"
    FV.REP = ""
    CALL OPF(FN.REP,FV.REP)
    RETURN

DETALLES:
    TOTAL.CUENTA = 0
    TOTAL.PROMEDIO = 0
    TOTAL.VOTOS = 0
*SEL.CMD = "SELECT " : FN.PA
*CALL EB.READLIST(SEL.CMD,SEL.LIST,'',NO.OF.RECS,SEL.ERR)
*LOOP REMOVE PA.ID FROM SEL.LIST SETTING STMT.POS
*WHILE PA.ID DO
*GOSUB GET.PARTIC
*REPEAT

    GOSUB GET.PARAMS
    Y.ASTERISK = "*"
    SEL.CMD.1 = "SELECT " : FN.REP : " WITH @ID EQ ASAMBLEA." :  Y.PARAM4[5,2] : "-" : Y.PARAM4[7,2] : "-" : Y.PARAM4[1,4]
    CALL EB.READLIST(SEL.CMD.1, ID.LIST.1, "", ID.CNT.1, ERR.SEL.1)

    LOOP
        REMOVE REC.ID FROM ID.LIST.1 SETTING ID.POS
    WHILE REC.ID:ID.POS
        CALL F.READ(FN.REP, REC.ID, R.REC, FV.REP, RD.ERR)
        IF R.REC THEN
            TOTAL.CUENTA = FIELD(R.REC,'|',1)
            TOTAL.PROMEDIO = FIELD(R.REC,'|',2)
            TOTAL.VOTOS = FIELD(R.REC,'|',3)
        END
    REPEAT

    RETURN

GET.PARTIC:
    CALL F.READ(FN.PA,PA.ID,R.PA, FV.PA, PA.ERR)
    IF R.PA NE '' THEN
        TOTAL.CUENTA += 1
        TOTAL.PROMEDIO += R.PA<ST.L.APA.BALANCE.PROM.ANU>
        TOTAL.VOTOS += R.PA<ST.L.APA.VOTOS.CUENTA>
    END
    RETURN

GET.PARAMS:
    CALL F.READ(FN.PARAM,"1",R.PARAM1, FV.PARAM, PA1.ERR)
    CALL F.READ(FN.PARAM,"2",R.PARAM2, FV.PARAM, PA2.ERR)
    CALL F.READ(FN.PARAM,"3",R.PARAM3, FV.PARAM, PA3.ERR)
    CALL F.READ(FN.PARAM,"4",R.PARAM4, FV.PARAM, PA4.ERR)

    Y.PARAM1 = R.PARAM1<2>
    Y.PARAM2 = R.PARAM2<2>
    Y.PARAM3 = R.PARAM3<2>
    Y.PARAM4 = R.PARAM4<2>

    RETURN

FINAL:
    Y.FINAL<-1> = TOTAL.CUENTA : "*" : TOTAL.PROMEDIO : "*" : TOTAL.VOTOS : "*" : Y.PARAM1 : "*" : Y.PARAM2 : "*": Y.PARAM3 : "*": Y.PARAM4
    RETURN

END
