*-----------------------------------------------------------------------------
* <Rating>-20</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE REDO.AZ.REINV.CONSULTA.LOAD

*
    $INCLUDE T24.BP I_COMMON
    $INCLUDE T24.BP I_EQUATE
    $INCLUDE T24.BP I_F.ACCOUNT
    $INCLUDE T24.BP I_F.AZ.ACCOUNT
    $INCLUDE LAPAP.BP I_REDO.AZ.REINV.CONSULTA.COMMON

    GOSUB INIT
    GOSUB GET.LOCREF
    RETURN

INIT:
*****
    FN.ACCOUNT = 'F.ACCOUNT'; F.ACCOUNT = ''
    CALL OPF(FN.ACCOUNT,F.ACCOUNT)
    FN.ACCOUNT.H = 'F.ACCOUNT$HIS'; F.ACCOUNT.H = ''
    CALL OPF(FN.ACCOUNT.H,F.ACCOUNT.H)
    FN.AZ.ACCOUNT = 'F.AZ.ACCOUNT'; F.AZ.ACCOUNT = ''
    CALL OPF(FN.AZ.ACCOUNT,F.AZ.ACCOUNT)
    FN.AZ.ACCOUNT.H = 'F.AZ.ACCOUNT$HIS'; F.AZ.ACCOUNT.H = ''
    CALL OPF(FN.AZ.ACCOUNT.H,F.AZ.ACCOUNT.H)
    FN.AZ.ACCT.BAL.HIST = 'F.AZ.ACCT.BAL.HIST'; F.AZ.ACCT.BAL.HIST = ''
    CALL OPF(FN.AZ.ACCT.BAL.HIST, F.AZ.ACCT.BAL.HIST)
    FN.DR.OPER.AZCONSL.WORKFILE = 'F.DR.OPER.AZCONSL.WORKFILE'; F.DR.OPER.AZCONSL.WORKFILE = ''
    CALL OPF(FN.DR.OPER.AZCONSL.WORKFILE,F.DR.OPER.AZCONSL.WORKFILE)
    L.AC.AZ.ACC.REF.POSN = ''; L.AC.REINVESTED.POSN = ''; YL.FIELD = ''; YL.APP = ''
    SEL.CMD.APP = ''; SEL.APP.LIST = ''; NO.OF.APP.RECS = ''; SEL.APP.ERR = ''
    RETURN

GET.LOCREF:
***********
    LOC.REF.APP = 'ACCOUNT'
    LOC.REF.FIELD = 'L.AC.AZ.ACC.REF':VM:'L.AC.REINVESTED'
    YLOC.REF = ''
    CALL MULTI.GET.LOC.REF(LOC.REF.APP,LOC.REF.FIELD,YLOC.REF)
    POS.AZ.ACC.REF          = YLOC.REF<1,1>
    L.AC.REINVESTED.POS     = YLOC.REF<1,2>
    RETURN

END
