*-----------------------------------------------------------------------------
* <Rating>-32</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE REDO.V.AA.VAL.CP.OVERPAY
*---------------------------------------------------------------------------------
* Description: This routine is to update the contact table REDO.AA.CP.OVERPAYMENT during the
*             VALIDATION stage of AA overpayment through CASH & CHEQUE version.
*
* Version Involved:
*              VERSION>FT,REDO.MULTI.AA.ACRP.UPD.TR
*              VERSION>FT,REDO.MULTI.AA.ACRP.UPD
* Dev By: V.P.Ashokkumar
*
* Date : 10/10/2016
*---------------------------------------------------------------------------------

    $INCLUDE T24.BP I_COMMON
    $INCLUDE T24.BP I_EQUATE
    $INCLUDE T24.BP I_F.ACCOUNT
    $INCLUDE T24.BP I_F.FUNDS.TRANSFER
    $INCLUDE TAM.BP I_F.REDO.AA.OVERPAYMENT

    GOSUB INIT
    GOSUB PROCESS
    RETURN

INIT:
*****
    FN.ACCOUNT = 'F.ACCOUNT'; F.ACCOUNT = ''
    CALL OPF(FN.ACCOUNT,F.ACCOUNT)
    FN.REDO.AA.OVERPAYMENT = 'F.REDO.AA.OVERPAYMENT'; F.REDO.AA.OVERPAYMENT = ''
    CALL OPF(FN.REDO.AA.OVERPAYMENT,F.REDO.AA.OVERPAYMENT)
    VAR.AA.ID = ''; FT.TXN.AMT = ''
    RETURN

PROCESS:
********
    VAR.AA.ID=R.NEW(FT.CREDIT.ACCT.NO)
    FT.TXN.AMT=R.NEW(FT.DEBIT.AMOUNT)
    IF FT.TXN.AMT EQ '' THEN
        FT.TXN.AMT = R.NEW(FT.CREDIT.AMOUNT)
    END
    R.ACCOUNT = ''; ACC.ERR = ''; ERR.REDO.AA.CP.OVERPAYMENT = ''; R.REDO.AA.CP.OVERPAYMENT = ''
    CALL F.READ(FN.ACCOUNT,VAR.AA.ID,R.ACCOUNT,F.ACCOUNT,ACC.ERR)
    Y.AA.ID  = R.ACCOUNT<AC.ARRANGEMENT.ID>
    Y.CUSTOMER.ID = R.ACCOUNT<AC.CUSTOMER>
    GOSUB GET.AA.BALANC
* Validated to check the equal sign.
    IF YPEND.AMOUNT EQ 0 OR FT.TXN.AMT GE YPEND.AMOUNT THEN
        ETEXT = 'AA-CANT.GT.THAN.SOURCE.AMOUNT'
        CALL STORE.END.ERROR
        RETURN
    END
    RETURN

GET.AA.BALANC:
**************
    OUTSTAND.PRIN.BAL = 0; YPEND.AMOUNT = 0; Y.GET.OVER.PAY.AMT = 0
    CALL REDO.S.GET.OUT.BALANCE(Y.AA.ID,OUTSTAND.PRIN.BAL)

    SEL.CMD.OVER = ''; SEL.LIST.OVER = ''; SEL.ERR = ''
    SEL.CMD.OVER = 'SELECT ':FN.REDO.AA.OVERPAYMENT:' WITH LOAN.NO EQ ':VAR.AA.ID:' AND STATUS EQ "PENDIENTE"'
    CALL EB.READLIST(SEL.CMD.OVER,SEL.LIST.OVER,'','',SEL.ERR)
    LOOP
        REMOVE OVER.ID FROM SEL.LIST.OVER SETTING OVER.POS
    WHILE OVER.ID:OVER.POS
        REDO.AA.OVERPAYMENT.ERR = ''; R.REDO.AA.OVERPAYMENT = ''
        CALL F.READ(FN.REDO.AA.OVERPAYMENT,OVER.ID,R.REDO.AA.OVERPAYMENT,F.REDO.AA.OVERPAYMENT,REDO.AA.OVERPAYMENT.ERR)
        Y.GET.OVER.PAY.AMT += R.REDO.AA.OVERPAYMENT<REDO.OVER.AMOUNT>
    REPEAT

    YPEND.AMOUNT = OUTSTAND.PRIN.BAL - Y.GET.OVER.PAY.AMT
    YPEND.AMOUNT = ABS(YPEND.AMOUNT)
    RETURN
END
