*-----------------------------------------------------------------------------
* <Rating>345</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE REDO.B.AA.ZBAL.NEG.VAL(ARR.LN.DATA)
*--------------------------------------------------------------------------------------------------
*  M O D I F I C A T I O N S
* ***************************
*--------------------------------------------------------------------------------------------------
* Defect Reference       Modified By                    Date of Change        Change Details
*
*                       Ashokkumar.V.P                  07/09/2015
*--------------------------------------------------------------------------------------------------
    $INCLUDE T24.BP I_COMMON
    $INCLUDE T24.BP I_EQUATE
    $INCLUDE T24.BP I_ENQUIRY.COMMON
    $INCLUDE T24.BP I_F.AA.ARRANGEMENT
    $INCLUDE T24.BP I_F.EB.CONTRACT.BALANCES
    $INCLUDE T24.BP I_GTS.COMMON
    $INCLUDE T24.BP I_F.AA.ACCOUNT.DETAILS
    $INCLUDE T24.BP I_F.AA.BILL.DETAILS
    $INCLUDE T24.BP I_F.AA.PAYMENT.SCHEDULE
    $INCLUDE T24.BP I_F.ACCOUNT
    $INCLUDE T24.BP I_F.AA.INTEREST.ACCRUALS
    $INCLUDE LAPAP.BP I_REDO.B.AA.ZBAL.NEG.VAL.COMMON
    $INCLUDE T24.BP I_F.AA.OVERDUE
    $INCLUDE T24.BP I_F.AA.ACTIVITY.HISTORY
    $INCLUDE TAM.BP I_F.REDO.APAP.PROPERTY.PARAM

    GOSUB MAIN.PROCESS
    RETURN

MAIN.PROCESS:
*************
    YFINAL.ARRY = ''
    LINE.TYP.C = "Cero_Cantidad_1"; LINE.TYP.P = "Saldo_Positivo_1"; LINE.TYP.N = "Saldo_Negativo_1"; LINE.TYP.ECB = "ECB_CERO_1"; LINE.TYP.ACC = "ACC_Cantidad_4"
    LINE.TYP.A = "Auth_Estado_1"; LINE.TYP.IR = "Cantidad_Devengo_2"; LINE.TYP.DDI = "Instrucciones_debito_directo_3"; LINE.TYP.NAB = "NAB_Positivo_1"
    AA.ID = ARR.LN.DATA
    ERR.AA.ARR = ''; R.AA.ARR = ''; Y.ACCOUNT = ''; Y.LINK.POS = ''
    CALL F.READ(FN.AA.ARR,AA.ID,R.AA.ARR,F.AA.ARR,ERR.AA.ARR)
    Y.MAIN.PROD.GROUP = R.AA.ARR<AA.ARR.PRODUCT.GROUP>
    Y.MAIN.ARR.STATUS = R.AA.ARR<AA.ARR.ARR.STATUS>
    Y.MAIN.ARR.PRCT = R.AA.ARR<AA.ARR.PRODUCT>
    Y.MAIN.STRT.DTE = R.AA.ARR<AA.ARR.START.DATE>
    IF Y.MAIN.STRT.DTE GT YLST.TODAY THEN
        RETURN
    END
    Y.CUSTOMER.ID = R.AA.ARR<AA.ARR.CUSTOMER>
    Y.CURRENCY    = R.AA.ARR<AA.ARR.CURRENCY>
    Y.LINKED.APPL = R.AA.ARR<AA.ARR.LINKED.APPL>
    Y.LINKED.APPL.ID = R.AA.ARR<AA.ARR.LINKED.APPL.ID>
    LOCATE "ACCOUNT" IN Y.LINKED.APPL<1,1> SETTING Y.LINK.POS THEN
        Y.ACCOUNT =Y.LINKED.APPL.ID<Y.LINK.POS>
    END

    R.ACCOUNT = ''; Y.ACC.ERR = ''; YCUSTOMER = ''; YOD.STAT = ''; YORG.ACTUAL.AMOUNT = 0
    CALL F.READ(FN.ACCOUNT,Y.ACCOUNT,R.ACCOUNT,F.ACCOUNT,Y.ACC.ERR)
    IF Y.ACC.ERR THEN
        RETURN
    END
    YOD.STAT = R.ACCOUNT<AC.LOCAL.REF,L.OD.STATUS.POS>
    YCUSTOMER = R.ACCOUNT<AC.CUSTOMER>
    YORG.ACTUAL.AMOUNT = R.ACCOUNT<AC.LOCAL.REF,POS.AVL.BAL>
    ARRAY.VAL = ''; Y.LOAN.STATUS = ''; Y.CLOSE.LN.FLG = 0
    GOSUB GET.LOAN.STATUS
    GOSUB GET.CLOSED.LOAN.CHK
    GOSUB PROCESS.ECB
    GOSUB CLSE.ACCT.CHK
    RETURN

PROCESS.ECB:
************
    R.EB.CON.BAL = ''; ERR.EB.CON.BAL = ''; ACCTP.VAL = 0; TACCT.VAL = 0; YUNC.VAL = 0; ACCTPP.VAL = 0; Y.BAL.PRIC.GP = ''
    MACCT.VAL = 0; CACCT.VAL = 0; DATE.LSTUPD = 0; TNAB.ACCT.VAL = 0;  YARR.ASST = ''; YARR.ASSTORG = ''; MRACCT.VAL = 0
    Y.BAL.PRIC.ORG = ''; ECB.TACCT.VAL = 0; ECB.ACCTP.VAL = 0; ECB.MACCT.VAL = 0; ECB.CACCT.VAL = 0; ECB.MRACCT.VAL = 0; ACCTPP.VAL = 0
    TPACCT.VAL = 0; MPACCT.VAL = 0; CPACCT.VAL = 0; MRPACCT.VAL = 0; ACC.PRINVAL = 0; ACC.PENVAL = 0; YFIN.AMT = 0; ECB.ACCTP.VALN = 0
    CALL F.READ(FN.EB.CON.BAL,Y.ACCOUNT,R.EB.CON.BAL,F.EB.CON.BAL,EB.CON.BAL.ERR)
    IF NOT(R.EB.CON.BAL) THEN
        RETURN
    END
    ERR.PSEB = ''; R.REDO.AA.POSIT.SIGN.ECB.BAL = ''; YFLD1 = ''; YFLD2 = ''; YFLD3 = ''; YTMP.BAL.VALO = ''
    YFLD4 = ''; YFLD5 = ''; YFLD6 = ''; YFLD7 = ''; YTMP.BAL.TYPE = ''; YTMP.BAL.VAL = ''
    DATE.LSTUPD = R.EB.CON.BAL<ECB.DATE.LAST.UPDATE>
    Y.CNT.EB.CON = '1'
    Y.CUR.ASSET.TYPE = R.EB.CON.BAL<ECB.CURR.ASSET.TYPE>
    Y.DCNT.CUR.ASS = DCOUNT(Y.CUR.ASSET.TYPE,VM)
    Y.CNT.CUR.TYPE = '1'
    LOOP
    WHILE Y.CNT.CUR.TYPE LE Y.DCNT.CUR.ASS
        Y.TYPE.SYSDATE = ''; Y.PRIC.POS = ''; SYS.DATE = ''
        Y.ASSET.TYPE = Y.CUR.ASSET.TYPE<1,Y.CNT.CUR.TYPE>
        Y.TYPE.SYSDATE = R.EB.CON.BAL<ECB.TYPE.SYSDATE,Y.CNT.CUR.TYPE>
        YSYSTYPE = FIELD(Y.TYPE.SYSDATE,'-',1)
        SYS.DATE = FIELD(Y.TYPE.SYSDATE,'-',2)
        IF SYS.DATE <= YLST.TODAY THEN
            GOSUB CREDIT.MVMT.APPL
        END
        Y.CNT.CUR.TYPE += 1
    REPEAT
    WRK.FILE.ID = ''; LINE.TYP = ''
    GOSUB PRICNI.MVMT.APPL
    YFIN.AMT = 0
    YFIN.AMT = ACCTPP.VAL + TPACCT.VAL + MPACCT.VAL + CPACCT.VAL + MRPACCT.VAL

    IF (ACC.PRINVAL NE 0 OR ACC.PENVAL NE 0) AND Y.CLOSE.LN.FLG EQ 1 THEN
        RETURN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YOD.STAT:"**":ACC.PRINVAL:"*":ACC.PENVAL:"***":YORG.ACTUAL.AMOUNT:"**":LINE.TYP.ACC
        LINE.TYP = LINE.TYP.ACC
        GOSUB WRITE.ARRY
    END
    IF YORG.ACTUAL.AMOUNT EQ 0 AND ACCTPP.VAL EQ 0 AND YUNC.VAL EQ 0 AND TPACCT.VAL EQ 0 AND MPACCT.VAL EQ 0 AND CPACCT.VAL EQ 0 AND MRPACCT.VAL EQ 0 THEN
        RETURN
    END
    Y.ACCTP.VAL = 0
    Y.ACCTP.VAL = ECB.ACCTP.VAL - YUNC.VAL
    IF YUNC.VAL LT 0 THEN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YOD.STAT:"*":YUNC.VAL:"*******":LINE.TYP.N
        LINE.TYP = LINE.TYP.N
        GOSUB WRITE.ARRY
        RETURN
    END
    IF (Y.ACCTP.VAL GT 0 OR ECB.TACCT.VAL GT 0 OR ECB.MACCT.VAL GT '0' OR ECB.MRACCT.VAL GT '0' OR ECB.CACCT.VAL GT '0') AND TNAB.ACCT.VAL EQ '0' THEN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YOD.STAT:"*":Y.ACCTP.VAL:"*":ECB.TACCT.VAL:"*":ECB.CACCT.VAL:"*":ECB.MRACCT.VAL:"*":ECB.MACCT.VAL:"**":ECB.ACCTP.VALN:"*":LINE.TYP.P
        LINE.TYP = LINE.TYP.P
        GOSUB WRITE.ARRY
        RETURN
    END
    IF (Y.ACCTP.VAL GT 0 OR ECB.TACCT.VAL GT 0 OR ECB.MACCT.VAL GT '0' OR ECB.MRACCT.VAL GT '0' OR ECB.CACCT.VAL GT '0' OR TNAB.ACCT.VAL GT '0') THEN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YOD.STAT:"*":Y.ACCTP.VAL:"*":ECB.TACCT.VAL:"*":ECB.CACCT.VAL:"*":ECB.MRACCT.VAL:"*":ECB.MACCT.VAL:"**":ECB.ACCTP.VALN:"*":LINE.TYP.NAB
        LINE.TYP = LINE.TYP.NAB
        GOSUB WRITE.ARRY
        RETURN
    END
    IF (ACCTPP.VAL NE 0 OR TPACCT.VAL NE 0 OR MPACCT.VAL NE 0 OR MRPACCT.VAL NE 0 OR CPACCT.VAL NE 0) AND Y.MAIN.ARR.STATUS EQ 'AUTH' THEN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YOD.STAT:"*":ACCTPP.VAL:"*":TPACCT.VAL:"*":CPACCT.VAL:"*":MRPACCT.VAL:"*":MPACCT.VAL:"***":LINE.TYP.A
        LINE.TYP = LINE.TYP.A
        GOSUB WRITE.ARRY
        RETURN
    END
    IF ACCTPP.VAL EQ '0' AND (TPACCT.VAL NE '0' OR MPACCT.VAL NE '0' OR MRPACCT.VAL NE '0' OR CPACCT.VAL NE '0') THEN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YOD.STAT:"*":ACCTPP.VAL:"*":TPACCT.VAL:"*":CPACCT.VAL:"*":MRPACCT.VAL:"*":MPACCT.VAL:"***":LINE.TYP.C
        LINE.TYP = LINE.TYP.C
        GOSUB WRITE.ARRY
        RETURN
    END
    IF YORG.ACTUAL.AMOUNT NE 0 AND ACCTPP.VAL EQ 0 AND YUNC.VAL EQ 0 AND TPACCT.VAL EQ 0 AND MPACCT.VAL EQ 0 AND CPACCT.VAL EQ 0 AND MRPACCT.VAL EQ 0 THEN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YOD.STAT:"**":TPACCT.VAL:"*":CPACCT.VAL:"*":MRPACCT.VAL:"*":MPACCT.VAL:"*":YORG.ACTUAL.AMOUNT:"**":LINE.TYP.ECB
        LINE.TYP = LINE.TYP.ECB
        GOSUB WRITE.ARRY
    END
    RETURN

WRITE.ARRY:
***********
    WRK.FILE.ID = AA.ID:'.':LINE.TYP
    CALL F.WRITE(FN.DR.REG.AA.PROB.WORKFILE,WRK.FILE.ID,YFINAL.ARRY)
    YFINAL.ARRY = ''
    RETURN

CLSE.ACCT.CHK:
**************
    IF Y.CLOSE.LN.FLG EQ 1 AND (YORG.ACTUAL.AMOUNT NE 0 OR YFIN.AMT EQ 0) THEN
        RETURN
    END
    IF YFIN.AMT EQ 0 THEN
        RETURN
    END
    IF (Y.MAIN.ARR.STATUS NE 'PENDING.CLOSURE' AND Y.MAIN.ARR.STATUS NE 'CLOSED' AND Y.MAIN.ARR.STATUS NE 'AUTH') THEN
        GOSUB INT.ACCR
        GOSUB GET.DIRECT.DB
    END
    RETURN

INT.ACCR:
*********
    IF Y.CLOSE.LN.FLG EQ 1 THEN
        RETURN
    END

    ACCRUL.ID = AA.ID:"-PRINCIPALINT"
    GOSUB READ.ACCRUAL
    YTO.DATE = R.AA.INTEREST.ACCRUALS<AA.INT.ACC.TO.DATE,1>

    IF Y.MAIN.ARR.STATUS EQ 'EXPIRED' THEN
        RETURN
        YTTO.DATE = YTO.DATE
        ACCRUL.ID = AA.ID:"-PENALTINT"
        GOSUB READ.ACCRUAL
        YTO.DATE = R.AA.INTEREST.ACCRUALS<AA.INT.ACC.TO.DATE,1>
        IF NOT(YTO.DATE) THEN
            YTO.DATE = YTTO.DATE
        END
    END

    IF (NOT(YTO.DATE) OR YTO.DATE LT YLST.TODAY) THEN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YTO.DATE:"*":Y.MAIN.PROD.GROUP:"*":TOTCOMMITMENT.VAL:"*":ACCTPP.VAL
        LINE.TYP = LINE.TYP.IR
        GOSUB WRITE.ARRY
    END
    RETURN

READ.ACCRUAL:
**************
    R.AA.INTEREST.ACCRUALS = ''; ERR.ACCRUAL = ''; YTO.DATE = ''
    CALL F.READ(FN.AA.INTEREST.ACCRUALS,ACCRUL.ID,R.AA.INTEREST.ACCRUALS,F.AA.INTEREST.ACCRUALS,ERR.ACCRUAL)
    RETURN

GET.ECB.BAL:
************
    BAL.DETAILS = ''; ERROR.MESSAGE = ''
    CALL AA.GET.PERIOD.BALANCES(Y.ACCOUNT, BAL.TYPE1,REQUEST.TYPE, START.DATE, END.DATE, '',BAL.DETAILS, ERROR.MESSAGE)
    RETURN

GET.DIRECT.DB:
**************
    GOSUB AA.PAYMENT.SCHEDULE.READ
    IF Y.STATUS.DD NE "Direct Debit" THEN
        IF Y.DEBIT.ACCT EQ '' THEN
            RETURN
        END
    END
    R.ACCOUNT.DETAILS = ''; ERR.ACC = ''
    CALL F.READ(FN.AA.ACCOUNT.DETAILS,AA.ID,R.ACCOUNT.DETAILS,F.AA.ACCOUNT.DETAILS,ERR.ACC)
    Y.BILL.LIST    = R.ACCOUNT.DETAILS<AA.AD.BILL.ID>
    Y.BILL.TYPE    = R.ACCOUNT.DETAILS<AA.AD.BILL.TYPE>
    Y.BILL.STATUS  = R.ACCOUNT.DETAILS<AA.AD.SET.STATUS>
    Y.BILL.SETCNT = R.ACCOUNT.DETAILS<AA.AD.BILLS.SETTLED.CNT>

    CHANGE SM TO FM IN  Y.BILL.LIST
    CHANGE SM TO FM IN  Y.BILL.TYPE
    CHANGE SM TO FM IN  Y.BILL.STATUS

    CHANGE VM TO FM IN  Y.BILL.LIST
    CHANGE VM TO FM IN  Y.BILL.TYPE
    CHANGE VM TO FM IN  Y.BILL.STATUS

    Y.BILL.LIST.ID = ''; Y.TOT.AMT = 0; YOS.TOT.AMT = 0; YTOT.IMPUSTO = 0; YFINAL.AMT = 0
    YBILL.CNT = DCOUNT(Y.BILL.LIST,FM)
    IF YBILL.CNT GT Y.BILL.SETCNT THEN
        GOSUB GET.BILL.SETT.DETAILS
    END

    IF (Y.TOT.AMT AND Y.ACTUAL.AMOUNT GE YFINAL.AMT) THEN
        YFINAL.ARRY = AA.ID:"*":Y.ACCOUNT:"*":Y.MAIN.ARR.STATUS:"*":Y.LOAN.STATUS:"*":YL.LOAN.COND:"*":YCUSTOMER:"*":Y.TOT.AMT:"*":YOS.TOT.AMT:"*":YTOT.IMPUSTO:"*":Y.BILL.DTE:"*":Y.DEBIT.ACCT:"*":YDD.CUSTOMER:"*":Y.ACTUAL.AMOUNT
        LINE.TYP = LINE.TYP.DDI
        GOSUB WRITE.ARRY
    END
    RETURN

GET.BILL.SETT.DETAILS:
**********************
    Y.CNT = Y.BILL.SETCNT + 1
    LOOP
    WHILE Y.CNT LE YBILL.CNT
        IF Y.BILL.STATUS<Y.CNT> EQ 'UNPAID' AND Y.BILL.TYPE<Y.CNT> EQ 'PAYMENT' THEN
            Y.BILL.ID = Y.BILL.LIST<Y.CNT>
            GOSUB FT.PROCESS
            Y.CNT = YBILL.CNT
        END
        Y.CNT = Y.CNT + 1
    REPEAT
    RETURN

FT.PROCESS:
*----------
    Y.TOT.AMT = 0; R.AA.BILL.DETAILS = ''; Y.ERR.BILL = ''; Y.BILL.DTE = ''; YOS.TOT.BILL.AMT = 0; YOS.TOT.AMT = 0
    CALL F.READ(FN.AA.BILL.DETAILS,Y.BILL.ID,R.AA.BILL.DETAILS,F.AA.BILL.DETAILS,Y.ERR.BILL)
    Y.TOT.BILL.AMT = R.AA.BILL.DETAILS<AA.BD.OR.TOTAL.AMOUNT>
    YOS.TOT.BILL.AMT = SUM(R.AA.BILL.DETAILS<AA.BD.OS.PROP.AMOUNT>)
    YOS.TOT.AMT = SUM(YOS.TOT.BILL.AMT)
    Y.BILL.DTE = R.AA.BILL.DETAILS<AA.BD.PAYMENT.DATE>
    Y.TOT.AMT = ABS(Y.TOT.BILL.AMT)
    YTOT.IMPUSTO = YOS.TOT.AMT * 0.0015
    YFINAL.AMT = YOS.TOT.AMT + YTOT.IMPUSTO
    RETURN

AA.PAYMENT.SCHEDULE.READ:
**-----------------------
    ARRANGEMENT.ID   = AA.ID
    PROP.CLASS       = 'PAYMENT.SCHEDULE'
    PROP.NAME  = '';  RET.ERR = ''; returnConditions = ''; R.AA.PAYMENT.SCHEDULE = ''
    Y.DEBIT.ACCT = ''; Y.STATUS.DD  = ''
    CALL AA.GET.ARRANGEMENT.CONDITIONS(ARRANGEMENT.ID,PROP.CLASS,PROP.NAME,'','',returnConditions,RET.ERR)
    R.AA.PAYMENT.SCHEDULE = RAISE(returnConditions)
    IF R.AA.PAYMENT.SCHEDULE THEN
        Y.DEBIT.ACCT = R.AA.PAYMENT.SCHEDULE<AA.PS.LOCAL.REF><1,DEBIT.ACCT.POS>
        Y.STATUS.DD  = R.AA.PAYMENT.SCHEDULE<AA.PS.LOCAL.REF><1,PAYMT.METHOD.POS>
    END
    RDD.ACCOUNT = ''; YDD.ACC.ERR = ''; YDD.CUSTOMER = '';  Y.TRANSIT.AMOUNT = 0; Y.ACTUAL.AMOUNT = 0
    CALL F.READ(FN.ACCOUNT,Y.DEBIT.ACCT,RDD.ACCOUNT,F.ACCOUNT,YDD.ACC.ERR)
    YDD.CUSTOMER = RDD.ACCOUNT<AC.CUSTOMER>
    Y.TRANSIT.AMOUNT = RDD.ACCOUNT<AC.LOCAL.REF,POS.TRANS.AMT>
    Y.ACTUAL.AMOUNT = RDD.ACCOUNT<AC.LOCAL.REF,POS.AVL.BAL> + Y.TRANSIT.AMOUNT
    RETURN

PRICNI.MVMT.APPL:
*---------------
    YARR.CNT = 0; X = 1; TOTCOMMITMENT.VAL = 0
    YARR.CNT = DCOUNT(YARR.ASST,FM)
    LOOP
    UNTIL X GT YARR.CNT
        ECB.AMT = 0; ORG.ECB.AMT = 0; ASSET.VAL = ''; TEMP.FLG = 0
        ASSET.VAL = YARR.ASST<X>
        ECB.AMT = Y.BAL.PRIC.GP<X>
        ORG.ECB.AMT = Y.BAL.PRIC.ORG<X>
        TEMP.ASST = ASSET.VAL[4,99]
        IF ORG.ECB.AMT EQ 0 THEN
            X++
            CONTINUE
        END

        IF TEMP.ASST EQ "PRINCIPALINT" OR ASSET.VAL EQ "PRINCIPALINT" THEN
            TACCT.VAL += ECB.AMT
            IF ORG.ECB.AMT GT 0 AND ASSET.VAL[1,3] EQ 'NAB' THEN
                TNAB.ACCT.VAL += ORG.ECB.AMT
            END
            IF ORG.ECB.AMT GT 0 THEN
                ECB.TACCT.VAL += ORG.ECB.AMT
            END
            IF ORG.ECB.AMT THEN
                TPACCT.VAL += ORG.ECB.AMT
            END
            TEMP.FLG = 1
        END

        IF ASSET.VAL EQ "ACCPRINCIPALINT" THEN
            ACC.PRINVAL += ORG.ECB.AMT
        END
        IF ASSET.VAL EQ "ACCPENALTINT" THEN
            ACC.PENVAL += ORG.ECB.AMT
        END

        IF TEMP.ASST EQ "ACCOUNT" OR ASSET.VAL EQ "ACCOUNT" THEN
            ACCTP.VAL += ECB.AMT
            IF ORG.ECB.AMT GT 0 THEN
                ECB.ACCTP.VAL += ORG.ECB.AMT
            END
            IF ORG.ECB.AMT LT 0 AND ASSET.VAL NE 'UNCACCOUNT' THEN
                ECB.ACCTP.VALN += ORG.ECB.AMT
            END
            IF ORG.ECB.AMT THEN
                ACCTPP.VAL += ORG.ECB.AMT
            END
            TEMP.FLG = 1
        END

        IF TEMP.ASST EQ "PENALTINT" OR ASSET.VAL EQ "PENALTINT" THEN
            CACCT.VAL += ECB.AMT
            IF ORG.ECB.AMT GT 0 THEN
                ECB.CACCT.VAL += ORG.ECB.AMT
            END
            IF ORG.ECB.AMT THEN
                CPACCT.VAL += ORG.ECB.AMT
            END
            TEMP.FLG = 1
        END
        IF TEMP.ASST EQ "PRMORA" OR ASSET.VAL EQ "PRMORA" THEN
            MRACCT.VAL += ECB.AMT
            IF ORG.ECB.AMT GT 0 THEN
                ECB.MRACCT.VAL += ORG.ECB.AMT
            END
            IF ORG.ECB.AMT THEN
                MRPACCT.VAL += ORG.ECB.AMT
            END
            TEMP.FLG = 1
        END
        IF TEMP.FLG EQ 0 AND (TEMP.ASST[1,10] NE 'COMMITMENT' AND ASSET.VAL NE 'COMMITMENT') THEN
            MACCT.VAL += ECB.AMT
            IF ORG.ECB.AMT GT 0 THEN
                ECB.MACCT.VAL += ORG.ECB.AMT
            END
            IF ORG.ECB.AMT THEN
                MPACCT.VAL += ORG.ECB.AMT
            END
            TEMP.FLG = 1
        END
        IF ASSET.VAL EQ 'UNCACCOUNT' THEN
            YUNC.VAL += ORG.ECB.AMT
        END
        IF TEMP.ASST EQ "TOTCOMMITMENT" OR ASSET.VAL EQ 'TOTCOMMITMENT' THEN
            TOTCOMMITMENT.VAL = ORG.ECB.AMT
        END
        X++
    REPEAT
    RETURN

CREDIT.MVMT.APPL:
*---------------
    YFST.VAL = ''; YFST.VAL.CNT = ''; YBL.VAL = ''; BAL.DETAILS = ''
    YFLG.K = 0; Y.BAL.PRIC = 0; YFST.VAL1 = ''; YTMP.BAL.VALO = ''
    REQUEST.TYPE<4>='ECB'
    START.DATE = YLST.TODAY
    END.DATE=YLST.TODAY
    YFST.VAL = FIELD(Y.ASSET.TYPE,'-',1)
    YBL.VAL = RIGHT(YFST.VAL,2)
    IF YBL.VAL EQ 'BL' OR YBL.VAL EQ 'SP' THEN
        YFST.VAL.CNT = LEN(YFST.VAL) - 2
        YFST.VAL1 = LEFT(YFST.VAL,YFST.VAL.CNT)
        YFLG.K = 1
    END ELSE
        YFST.VAL1 = YFST.VAL
    END
    LOCATE YFST.VAL IN YARR.ASSTORG<1> SETTING V.POSN THEN
        RETURN
    END ELSE
        YARR.ASSTORG<-1> = YFST.VAL
    END
    ERROR.MESSAGE = ''; BALANCE.CHECK = ''
    BALANCE.TO.CHECK = YFST.VAL
    CALL AA.GET.PERIOD.BALANCES(Y.ACCOUNT, BALANCE.TO.CHECK,REQUEST.TYPE, START.DATE, END.DATE, '',BAL.DETAILS, ERROR.MESSAGE)
    IF BAL.DETAILS<4> EQ 0 THEN
        RETURN
    END
    YTEMP.BAL = 0
    IF YFLG.K NE 1 THEN
        YTEMP.BAL = BAL.DETAILS<4>
    END
    LOCATE YFST.VAL1 IN YARR.ASST<1> SETTING VSPOSN THEN
        Y.TEMP.VAL = 0; YFST.VAL = 0; YTEMP.VAL = 0
        YTEMP.VAL = Y.BAL.PRIC.GP<VSPOSN>
        YFST.VAL = Y.BAL.PRIC.ORG<VSPOSN>
        Y.TEMP.VAL = BAL.DETAILS<4> + YTEMP.VAL
        Y.BAL.PRIC.GP<VSPOSN> = Y.TEMP.VAL
        Y.BAL.PRIC.ORG<VSPOSN> = YFST.VAL + YTEMP.BAL
    END ELSE
        YARR.ASST<-1> = YFST.VAL1
        Y.BAL.PRIC.GP<-1> = BAL.DETAILS<4>
        Y.BAL.PRIC.ORG<-1> = YTEMP.BAL
    END
    RETURN


GET.LOAN.STATUS:
*--------------*
    ArrangementID = AA.ID
    idPropertyClass = 'OVERDUE'; Y.LOAN.STATUS = ''; YL.LOAN.COND = ''
    idProperty = ''; returnIds = ''; returnConditions = ''; returnError = ''; effectiveDate = ''
    CALL AA.GET.ARRANGEMENT.CONDITIONS(ArrangementID, idPropertyClass, idProperty, effectiveDate, returnIds, returnConditions, returnError)
    R.AA.OVERDUE = RAISE(returnConditions)
    Y.LOAN.STATUS = R.AA.OVERDUE<AA.OD.LOCAL.REF,Y.L.LOAN.STATUS.1.POS>
    YL.LOAN.COND = R.AA.OVERDUE<AA.OD.LOCAL.REF,L.LOAN.COND.POS>
    RETURN

GET.CLOSED.LOAN.CHK:
********************
    REQD.MODE = ''; EFF.DATE = Y.MAIN.STRT.DTE; R.AA.ACTIVITY.HISTORY = ''
    Y.CLOSE.LN.FLG = 0; YACT.IS.STAT = ''; YACT.ID.ARR = ''
    CALL AA.READ.ACTIVITY.HISTORY(AA.ID, REQD.MODE, EFF.DATE, R.AA.ACTIVITY.HISTORY)
    IF R.AA.ACTIVITY.HISTORY THEN
        YACT.ID.ARR = R.AA.ACTIVITY.HISTORY<AA.AH.ACTIVITY>
        YACT.IS.STAT = R.AA.ACTIVITY.HISTORY<AA.AH.ACT.STATUS>
        CHANGE VM TO FM IN YACT.ID.ARR
        CHANGE SM TO FM IN YACT.ID.ARR
        CHANGE VM TO FM IN YACT.IS.STAT
        CHANGE SM TO FM IN YACT.IS.STAT
    END
    Y.PROD.GUP = R.AA.ARR<AA.ARR.PRODUCT.GROUP>
    ERR.REDO.APAP.PROPERTY.PARAM = ''; R.REDO.APAP.PROPERTY.PARAM = ''; YPAYOFF.ACT = ''; YPAY.CNT = 0
    CALL F.READ(FN.REDO.APAP.PROPERTY.PARAM,Y.PROD.GUP,R.REDO.APAP.PROPERTY.PARAM,F.REDO.APAP.PROPERTY.PARAM,ERR.REDO.APAP.PROPERTY.PARAM)
    IF R.REDO.APAP.PROPERTY.PARAM THEN
        YPAYOFF.ACT = R.REDO.APAP.PROPERTY.PARAM<PROP.PARAM.PAYOFF.ACTIVITY>
        YPAY.CNT = DCOUNT(YPAYOFF.ACT,VM)
    END

    YCNT = 1
    LOOP
    WHILE YCNT LE YPAY.CNT
        YPAYOFF.ACT.1 = ''
        YPAYOFF.ACT.1 = R.REDO.APAP.PROPERTY.PARAM<PROP.PARAM.PAYOFF.ACTIVITY,YCNT>
        LOCATE YPAYOFF.ACT.1 IN YACT.ID.ARR<1> SETTING CHG.POSN.1 THEN
            YARR.STAT = YACT.IS.STAT<CHG.POSN.1>
            IF YARR.STAT EQ 'AUTH' THEN
                Y.CLOSE.LN.FLG = 1
                YCNT = YPAY.CNT + 1
                CONTINUE
            END
        END
        YCNT++
    REPEAT
    RETURN
END
