$PACKAGE APAP.LAPAP
SUBROUTINE REDO.B.M.PROP.NONRES.LOAD
*---------------------------------------------------------------------------------------------
*  M O D I F I C A T I O N S
* ***************************
*---------------------------------------------------------------------------------------------
*   Date       Author              Modification Description
* 29/10/2014  Ashokkumar.V.P        PACS00371996 - New mapping changes. Added L.COL.TOT.VALUA field
** 24-04-2023 R22 Auto Conversion - FM TO @FM, VM to @VM, SM to @SM
** 24-04-2023 Skanda R22 Manual Conversion - No changes
*---------------------------------------------------------------------------------------------

    $INSERT I_COMMON ;* R22 Auto conversion
    $INSERT I_EQUATE ;* R22 Auto conversion
    $INSERT I_F.CUSTOMER ;* R22 Auto conversion
    $INSERT I_F.AA.ARRANGEMENT ;* R22 Auto conversion
    $INSERT I_F.AA.TERM.AMOUNT ;* R22 Auto conversion
    $INSERT I_F.COLLATERAL ;* R22 Auto conversion
    $INSERT I_F.AA.ACCOUNT.DETAILS ;* R22 Auto conversion
    $INSERT I_F.AA.BILL.DETAILS ;* R22 Auto conversion
    $INSERT I_F.COUNTRY ;* R22 Auto conversion
    $INSERT I_F.REDO.CUSTOMER.ARRANGEMENT ;* R22 Auto conversion
    $INSERT I_F.REDO.H.REPORTS.PARAM ;* R22 Auto conversion
    $INSERT I_REDO.B.M.PROP.NONRES.COMMON ;* R22 Auto conversion
    $INSERT I_TSA.COMMON ;* R22 Auto conversion
    $INSERT I_BATCH.FILES ;* R22 Auto conversion
*
    GOSUB OPEN.PARA
    GOSUB MULTI.GET.LOC.REF
    GOSUB GET.PARAM.DETAILS
    GOSUB OPEN.TEMP.PATH

RETURN

OPEN.PARA:
*---------
    FN.CUSTOMER = 'F.CUSTOMER'
    F.CUSTOMER = ''
    CALL OPF(FN.CUSTOMER,F.CUSTOMER)

    FN.AA.ARRANGEMENT = 'F.AA.ARRANGEMENT'
    F.AA.ARRANGEMENT = ''
    CALL OPF(FN.AA.ARRANGEMENT,F.AA.ARRANGEMENT)

    FN.AA.ARR.TERM.AMOUNT = 'F.AA.ARR.TERM.AMOUNT'
    F.AA.ARR.TERM.AMOUNT = ''
    CALL OPF(FN.AA.ARR.TERM.AMOUNT,F.AA.ARR.TERM.AMOUNT)

    FN.COLLATERAL = 'F.COLLATERAL'
    F.COLLATERAL = ''
    CALL OPF(FN.COLLATERAL,F.COLLATERAL)

    FN.AA.ACCOUNT.DETAILS = 'F.AA.ACCOUNT.DETAILS'
    F.AA.ACCOUNT.DETAILS = ''
    CALL OPF(FN.AA.ACCOUNT.DETAILS,F.AA.ACCOUNT.DETAILS)

    FN.AA.BILL.DETAILS = 'F.AA.BILL.DETAILS'
    F.AA.BILL.DETAILS = ''
    CALL OPF(FN.AA.BILL.DETAILS,F.AA.BILL.DETAILS)

    FN.AA.BILL.DETAILS.HST = 'F.AA.BILL.DETAILS.HIST'
    F.AA.BILL.DETAILS.HST = ''
    CALL OPF(FN.AA.BILL.DETAILS.HST,F.AA.BILL.DETAILS.HST)

    FN.COUNTRY = 'F.COUNTRY'
    F.COUNTRY = ''
    CALL OPF(FN.COUNTRY,F.COUNTRY)

    FN.REDO.CUSTOMER.ARRANGEMENT = 'F.REDO.CUSTOMER.ARRANGEMENT'
    F.REDO.CUSTOMER.ARRANGEMENT = ''
    CALL OPF(FN.REDO.CUSTOMER.ARRANGEMENT,F.REDO.CUSTOMER.ARRANGEMENT)

    FN.REDO.H.REPORTS.PARAM = 'F.REDO.H.REPORTS.PARAM'
    F.REDO.H.REPORTS.PARAM = ''
    CALL OPF(FN.REDO.H.REPORTS.PARAM,F.REDO.H.REPORTS.PARAM)

RETURN

MULTI.GET.LOC.REF:
*-----------------
    Y.POS = ''
    Y.APPLICATION = 'AA.ARR.TERM.AMOUNT':@FM:'COLLATERAL'
    Y.FIELDS = 'L.AA.COL':@FM:'L.COL.TOT.VALUA'
    CALL MULTI.GET.LOC.REF(Y.APPLICATION,Y.FIELDS,Y.POS)
    Y.L.AA.COL.POS = Y.POS<1,1>
    Y.L.CO.LOAN.AMT.POS = Y.POS<2,1>

RETURN

GET.PARAM.DETAILS:
*-----------------

    REDO.H.REPORTS.PARAM.ID = 'REDO.B.M.PROP.NON.RES'

    R.REDO.H.REPORTS.PARAM = ''; REDO.PARAM.ERR = ''
    CALL CACHE.READ(FN.REDO.H.REPORTS.PARAM,REDO.H.REPORTS.PARAM.ID,R.REDO.H.REPORTS.PARAM,REDO.PARAM.ERR)

    IF REDO.H.REPORTS.PARAM.ID THEN
        FILE.NAME = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.OUT.FILE.NAME>
        TEMP.PATH = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.TEMP.DIR>
        OUT.PATH = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.OUT.DIR>
        FIELD.NAME = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.FIELD.NAME>
        FIELD.VALUE = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.FIELD.VALUE>
        DISPLAY.TEXT = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.DISPLAY.TEXT>
        FILE.NAME = FILE.NAME:".TEMP.":AGENT.NUMBER:".":SERVER.NAME ;* R22 Auto conversion
        PARAM.FIELD.NAME = CHANGE(FIELD.NAME,@VM,@FM)
    END

    LOCATE 'RESIDENCE.NE' IN FIELD.NAME<1,1> SETTING FL.FOUND.POS THEN
        FL.PARAM.RES.NE = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.FIELD.VALUE,FL.FOUND.POS>
    END

    LOCATE 'PRODUCT.LINE.EQ' IN FIELD.NAME<1,1> SETTING FL.FOUND.POS1 THEN
        FL.PARAM.PRD.LINE = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.FIELD.VALUE,FL.FOUND.POS1>
    END

    LOCATE 'PRODUCT.GROUP.EQ' IN FIELD.NAME<1,1> SETTING FL.FOUND.POS2 THEN
        FL.PARAM.PRD.GRP = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.FIELD.VALUE,FL.FOUND.POS2>
    END

    LOCATE 'ARR.STATUS' IN FIELD.NAME<1,1> SETTING FL.FOUND.POS3 THEN
        FL.PARAM.ARR.STAUS = R.REDO.H.REPORTS.PARAM<REDO.REP.PARAM.FIELD.VALUE,FL.FOUND.POS3>
        CHANGE @SM TO ' ' IN FL.PARAM.ARR.STAUS
    END
RETURN

OPEN.TEMP.PATH:
*--------------
    SEQ.PTR = ''
    OPENSEQ TEMP.PATH,FILE.NAME TO SEQ.PTR ELSE
        CREATE SEQ.PTR ELSE
            ERR.MSG = "Unable to open '":FILE.NAME:"'"
            INT.CODE = "REP001"
            INT.TYPE = "ONLINE"
            MON.TP = "04"
            REC.CON = "AA.NONRES-":ERR.MSG
            DESC = "AA.NONRES-":ERR.MSG
            CALL REDO.INTERFACE.REC.ACT(INT.CODE,INT.TYPE,BAT.NO,BAT.TOT,INFO.OR,INFO.DE,ID.PROC,MON.TP,DESC,REC.CON,EX.USER,EX.PC)
        END
    END
*
RETURN
END
