* @ValidationCode : MjoxMzUxNTIxMTcyOkNwMTI1MjoxNjgyMzI0MjcxNTQ3OmFqaXRoOi0xOi0xOjA6MDpmYWxzZTpOL0E6UjIxX0FNUi4wOi0xOi0x
* @ValidationInfo : Timestamp         : 24 Apr 2023 13:47:51
* @ValidationInfo : Encoding          : Cp1252
* @ValidationInfo : User Name         : ajith
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : N/A
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : N/A
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R21_AMR.0
* @ValidationInfo : Copyright Temenos Headquarters SA 1993-2021. All rights reserved.
$PACKAGE APAP.LAPAP
SUBROUTINE DR.REG.PASIVAS.CONCAT.LOAD
*-----------------------------------------------------------------------------
* Company Name   : APAP
* Developed By   : gangadhar@temenos.com
* Program Name   : DR.REG.PASIVAS.CONCAT
* Date           : 27-May-2013
*-----------------------------------------------------------------------------
* Description:
*------------
* This multi-thread job is meant for to extact the Active Interest rates
*-----------------------------------------------------------------------------
*
* Modification History :
* ----------------------
*   Date          Author           Modification Description
*
* 05-Aug-2014  Ashokkumar.V.P      PACS00305233:- Removed 8th range
* 09-Oct-2014  Ashokkumar.V.P      PACS00305233:- Changed the parameter values
* 16-Apr-2015  Ashokkumar.V.P      PACS00305233:- Changed for performance issue.
*---------------------------------------------------------------------------------------
*DATE               WHO                       REFERENCE                 DESCRIPTION
*24-04-2023       CONVERSION TOOLS            AUTO R22 CODE CONVERSION  REGREP.BP,LAPAP.BP,T24.BP is removed ,$INCLUDE to$INSERT ,VMto@VM ,FMto@FM
*24-04-2023       AJITHKUMAR                  MANUAL R22 CODE CONVERSION NO CHANGE
*----------------------------------------------------------------------------------------
*-----------------------------------------------------------------------------

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_BATCH.FILES
    $INSERT I_F.DATES

    $INSERT I_DR.REG.PASIVAS.CONCAT.COMMON
    $INSERT I_F.DR.REG.PASIVAS.PARAM

    GOSUB INIT.VAR
    GOSUB INIT.PROCESS
RETURN

INIT.PROCESS:
*************
    CALL OPF(FN.CUSTOMER,F.CUSTOMER)
    CALL OPF(FN.DR.REG.PASIVAS.GROUP,F.DR.REG.PASIVAS.GROUP)
    CALL OPF(FN.BASIC.INTEREST,F.BASIC.INTEREST)
    CALL OPF(FN.GROUP.DATE,F.GROUP.DATE)
    CALL OPF(FN.AZ.ACCOUNT,F.AZ.ACCOUNT)
    CALL OPF(FN.ACCOUNT,F.ACCOUNT)
    CALL OPF(FN.PERIODIC.INTEREST,F.PERIODIC.INTEREST)
    CALL OPF(FN.AZ.PRODUCT.PARAMETER,F.AZ.PRODUCT.PARAMETER)
    CALL OPF(FN.DR.REG.PASIVAS.PARAM,F.DR.REG.PASIVAS.PARAM)
    CALL OPF(FN.ACCOUNT.CREDIT.INT,F.ACCOUNT.CREDIT.INT)
    CALL OPF(FN.GROUP.CREDIT.INT,F.GROUP.CREDIT.INT)
    CALL OPF(FN.ACCT.ENT.LWORK.DAY,F.ACCT.ENT.LWORK.DAY)
    CALL OPF(FN.STMT.ENTRY,F.STMT.ENTRY)

    LAST.WORK.DAY = R.DATES(EB.DAT.LAST.WORKING.DAY)
    CALL CACHE.READ(FN.DR.REG.PASIVAS.PARAM,'SYSTEM',R.DR.REG.PASIVAS.PARAM,DR.REG.PASIVAS.PARAM.ERR)
    CAT.LIST = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.CATEGORY>
    CAT.LIST1 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.GRP14.CATEGORY>
    CAT.LIST2 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.GRP15.CATEGORY>
    CAT.LIST3 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.GRP16.CATEGORY>
    CHANGE @VM TO @FM IN CAT.LIST3
    REL.CHK.LIST = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.BANK.EMP.REL>
    CHANGE @VM TO @FM IN REL.CHK.LIST
    GRP1.VAL = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.GROUP.SEL,1>
    GRP2.VAL = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.GROUP.SEL,2>
    GRP3.VAL = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.GROUP.SEL,3>

    RANGE1 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.RANGE.DAYS,1>
    RANGE2 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.RANGE.DAYS,2>
    RANGE3 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.RANGE.DAYS,3>
    RANGE4 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.RANGE.DAYS,4>
    RANGE5 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.RANGE.DAYS,5>
    RANGE6 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.RANGE.DAYS,6>
    RANGE7 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.RANGE.DAYS,7>

    MM.RANGE1 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.MM.RANGE.DAYS,1>
    MM.RANGE2 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.MM.RANGE.DAYS,2>
    MM.RANGE3 = R.DR.REG.PASIVAS.PARAM<DR.PASIVAS.PARAM.MM.RANGE.DAYS,3>
RETURN

INIT.VAR:
*********
    FN.CUSTOMER = 'F.CUSTOMER' ; F.CUSTOMER = ''
    FN.DR.REG.PASIVAS.GROUP = 'F.DR.REG.PASIVAS.GROUP' ; F.DR.REG.PASIVAS.GROUP = ''
    FN.BASIC.INTEREST = 'F.BASIC.INTEREST' ; F.BASIC.INTEREST = ''
    FN.GROUP.DATE = 'F.GROUP.DATE' ; F.GROUP.DATE = ''
    FN.AZ.ACCOUNT = 'F.AZ.ACCOUNT' ; F.AZ.ACCOUNT = ''
    FN.ACCOUNT = 'F.ACCOUNT' ; F.ACCOUNT = ''
    FN.PERIODIC.INTEREST = 'F.PERIODIC.INTEREST'  ; F.PERIODIC.INTEREST = ''
    FN.AZ.PRODUCT.PARAMETER = 'F.AZ.PRODUCT.PARAMETER' ; F.AZ.PRODUCT.PARAMETER = ''
    FN.DR.REG.PASIVAS.PARAM = 'F.DR.REG.PASIVAS.PARAM' ; F.DR.REG.PASIVAS.PARAM = ''
    FN.ACCOUNT.CREDIT.INT = 'F.ACCOUNT.CREDIT.INT' ; F.ACCOUNT.CREDIT.INT = ''
    FN.GROUP.CREDIT.INT = 'F.GROUP.CREDIT.INT' ; F.GROUP.CREDIT.INT = ''
    FN.ACCT.ENT.LWORK.DAY = 'F.ACCT.ENT.LWORK.DAY'; F.ACCT.ENT.LWORK.DAY = ''
    FN.STMT.ENTRY = 'F.STMT.ENTRY'; F.STMT.ENTRY = ''

    LAST.WORK.DAY = ''; DR.REG.PASIVAS.PARAM.ERR = ''; R.DR.REG.PASIVAS.PARAM = ''
    CAT.LIST = ''; CAT.LIST1 = ''; CAT.LIST2 = ''; CAT.LIST3 = ''
    REL.CHK.LIST = ''; GRP1.VAL = ''; GRP2.VAL = ''; GRP3.VAL = ''
    RANGE1 = ''; RANGE2 = ''; RANGE3 = ''; RANGE4 = ''; RANGE5 = ''
    RANGE6 = ''; RANGE7 = ''; MM.RANGE1 = ''; MM.RANGE2 = ''; MM.RANGE3 = ''
RETURN

END
