$PACKAGE APAP.TAM

** 19-04-2023 R22 Auto Conversion no changes
** 19-04-2023 Skanda R22 Manual Conversion - No changes
SUBROUTINE REDO.VISA.NULL.OUTGOING.FLD

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.REDO.VISA.OUTGOING


    R.NEW(VISA.OUT.DOCUMENT.INDICATOR)=''
    R.NEW( VISA.OUT.MEMBER.MESSAGE.TXT)=''
    R.NEW( VISA.OUT.DEST.AMT)=''

RETURN

END
