* @ValidationCode : MjotMTcwMDk4MTI3NDpDcDEyNTI6MTY4MTM2ODQwNjQ5NDpJVFNTOi0xOi0xOjA6MDpmYWxzZTpOL0E6UjIxX0FNUi4wOi0xOi0x
* @ValidationInfo : Timestamp         : 13 Apr 2023 12:16:46
* @ValidationInfo : Encoding          : Cp1252
* @ValidationInfo : User Name         : ITSS
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : N/A
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : N/A
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R21_AMR.0
* @ValidationInfo : Copyright Temenos Headquarters SA 1993-2021. All rights reserved.
$PACKAGE APAP.REDOENQ
SUBROUTINE REDO.NOFILE.AI.UPD.FT.EXCEPTION(LIST.FT.EXCEP)

*-----------------------------------------------------------------------------
* Company Name : ASOCIACION POPULAR DE AHORROS Y PRESTAMOS
* Developed By : Prabhu N
* Program Name :
*-----------------------------------------------------------------------------
* Description    :  This Nofile routine will get required details of Customer Accts
* Linked with    :
* In Parameter   :
* Out Parameter  :
*-----------------------------------------------------------------------------
*------------------------------------------------------------------------
* Modification History :
*------------------------------------------------------------------------
*  DATE             WHO                   REFERENCE                  
* 13-APRIL-2023      Conversion Tool       R22 Auto Conversion  - Added IF E EQ "EB-UNKNOWN.VARIABLE" THEN , F.READ to CACHE.READ , VM to @VM 
* 13-APRIL-2023      Harsha                R22 Manual Conversion - No changes   
*-----------------------------------------------------------------------------
    $INSERT I_COMMON
    $INSERT I_System
    $INSERT I_EB.EXTERNAL.COMMON
    $INSERT I_F.CUSTOMER.ACCOUNT
    $INSERT I_F.REDO.APAP.STO.DUPLICATE
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.FT.TXN.TYPE.CONDITION
    $INSERT I_F.STANDING.ORDER
    $INSERT I_F.AI.REDO.ARCIB.PARAMETER

*---------*
MAIN.PARA:
*---------*
    GOSUB INITIALISE
    GOSUB OPEN.FILES
    GOSUB PROCESS

RETURN
*----------*
INITIALISE:
*----------*
    FN.FUNDS.TRANSFER.EXCEP = "F.FUNDS.TRANSFER$NAU"
    F.FUNDS.TRANSFER.EXCEP  = ''
    FN.FT.TXN.TYPE.CONDITION = 'F.FT.TXN.TYPE.CONDITION'
    F.FT.TXN.TYPE.CONDITION = ''
    FN.STO.DUP.EXCEP = 'F.REDO.APAP.STO.DUPLICATE$NAU'
    F.STO.DUP.EXCEP = ''
    FN.STANDING.ORDER.EXCEP = 'F.STANDING.ORDER$NAU'
    F.STANDING.ORDER.EXCEP = ''

    FN.AI.REDO.ARCIB.PARAMETER = 'F.AI.REDO.ARCIB.PARAMETER'
    F.AI.REDO.ARCIB.PARAMETER  = ''

RETURN
*----------*
OPEN.FILES:
*----------*
    CALL OPF(FN.FUNDS.TRANSFER.EXCEP,F.FUNDS.TRANSFER.EXCEP)
    CALL OPF(FN.FT.TXN.TYPE.CONDITION,F.FT.TXN.TYPE.CONDITION)
    CALL OPF(FN.STO.DUP.EXCEP,F.STO.DUP.EXCEP)
    CALL OPF(FN.STANDING.ORDER.EXCEP,F.STANDING.ORDER.EXCEP)
    CALL OPF(FN.AI.REDO.ARCIB.PARAMETER,F.AI.REDO.ARCIB.PARAMETER)


    LREF.APP = 'FUNDS.TRANSFER'
    LREF.FIELDS = 'L.ACTUAL.VERSIO':@VM:'L.COMMENTS'
    LREF.POS=''
    CALL MULTI.GET.LOC.REF(LREF.APP,LREF.FIELDS,LREF.POS)
    Y.LOC.COMMENTS.POS = LREF.POS<1,2>

    CALL CACHE.READ(FN.AI.REDO.ARCIB.PARAMETER,'SYSTEM',R.AI.REDO.ARCIB.PARAMETER,AI.REDO.ARCIB.PARAMETER.ERR)

    Y.PAYROLL.TXN.CODE  = R.AI.REDO.ARCIB.PARAMETER<AI.PARAM.PAYROLL.TXN.CODE>
    Y.SUPPLIER.TXN.CODE = R.AI.REDO.ARCIB.PARAMETER<AI.PARAM.SUPPLIER.TXN.CODE>

RETURN

*--------*
PROCESS:
*--------*

    CUST.ID = System.getVariable("EXT.SMS.CUSTOMERS")
    IF E EQ "EB-UNKNOWN.VARIABLE" THEN	 ;*R22 Auto Conversion  - Added IF E EQ "EB-UNKNOWN.VARIABLE" THEN
        CUST.ID = ""
    END

    SEL.CMD = "SELECT ":FN.FUNDS.TRANSFER.EXCEP:" WITH DEBIT.CUSTOMER EQ ":CUST.ID:" AND RECORD.STATUS EQ INAO"
    CALL EB.READLIST(SEL.CMD,SEL.LIST1,'',SEL.NOR1,SEL.RET1)
    LOOP
        REMOVE FT.ID FROM SEL.LIST1 SETTING CUST.ACC.POS
    WHILE FT.ID:CUST.ACC.POS
        CALL F.READ(FN.FUNDS.TRANSFER.EXCEP,FT.ID,R.FUNDS.TRANSFER.EXCEP,F.FUNDS.TRANSFER.EXCEP,FT.HIS.ERR)
        IF NOT(FT.HIS.ERR) THEN
            Y.INPUTTER =  FIELD(R.FUNDS.TRANSFER.EXCEP<FT.INPUTTER>,'_',6)
            Y.TRANSACTION.TYPE = R.FUNDS.TRANSFER.EXCEP<FT.TRANSACTION.TYPE>
            IF Y.TRANSACTION.TYPE EQ Y.PAYROLL.TXN.CODE OR Y.TRANSACTION.TYPE EQ Y.SUPPLIER.TXN.CODE THEN
                Y.TRANSACTION.TYPE = R.FUNDS.TRANSFER.EXCEP<FT.TRANSACTION.TYPE>
                CALL CACHE.READ(FN.FT.TXN.TYPE.CONDITION, Y.TRANSACTION.TYPE, R.FT.TXN.TYPE.CONDITION, FTTC.ERR)	;*R22 Auto Conversion  - F.READ to CACHE.READ
                Y.DESCRIPTION = R.FT.TXN.TYPE.CONDITION<FT6.DESCRIPTION,LNGG>
                IF NOT(Y.DESCRIPTION) THEN
                    Y.DESCRIPTION  =  R.FT.TXN.TYPE.CONDITION<FT6.DESCRIPTION,1>
                END
                Y.DEBIT.ACCT.NO  = R.FUNDS.TRANSFER.EXCEP<FT.DEBIT.ACCT.NO>

                Y.FILE.NAME  = R.FUNDS.TRANSFER.EXCEP<FT.LOCAL.REF,Y.LOC.COMMENTS.POS>
                Y.FILE.REF = FIELD(Y.FILE.NAME,'.',3)
                Y.FILE.TYPE = Y.FILE.REF[LEN(Y.FILE.REF)-2,LEN(Y.FILE.REF)]
                Y.FILE.REF = Y.FILE.REF[1,LEN(Y.FILE.REF)-3]
                Y.USERNAME = FIELD(Y.FILE.NAME,'.',1)
                IF Y.FILE.NAME THEN
                    Y.FILE.NAME = Y.USERNAME:'.':Y.FILE.REF:'.':Y.FILE.TYPE

                END

                Y.DEBIT.AMOUNT   = R.FUNDS.TRANSFER.EXCEP<FT.DEBIT.AMOUNT>
                Y.VERSION        = R.FUNDS.TRANSFER.EXCEP<FT.LOCAL.REF,LREF.POS>
                LIST.FT.EXCEP<-1> = FT.ID:"@":Y.DESCRIPTION:"@":Y.DEBIT.ACCT.NO:"@":Y.FILE.NAME:"@":Y.DEBIT.AMOUNT:"@":Y.VERSION
            END
        END
    REPEAT

*  SEL.STO.CMD = "SELECT ":FN.STO.DUP.EXCEP:" WITH ORIGIN.ACCT.CUST EQ ":CUST.ID:" AND RECORD.STATUS EQ INAO"
*  CALL EB.READLIST(SEL.STO.CMD,SEL.STO.LIST1,'',SEL.STO.NOR1,SEL.STO.RET1)
*  LOOP
*       REMOVE STO.ID FROM SEL.STO.LIST1 SETTING STO.ACC.POS
* WHILE STO.ID:STO.ACC.POS
*    CALL F.READ(FN.STO.DUP.EXCEP,STO.ID,R.STO.DUP.EXCEP,F.STO.DUP.EXCEP,STO.HIS.ERR)
*    IF NOT(STO.HIS.ERR) THEN
*         Y.INPUTTER =  FIELD(R.STO.DUP.EXCEP<REDO.SO.INPUTTER>,'_',6)
*    IF Y.INPUTTER EQ 'ARCIB' THEN
*        Y.DESCRIPTION = R.STO.DUP.EXCEP<REDO.SO.PAYMENT.DETAILS>
*        Y.DEBIT.ACCT.NO  = R.STO.DUP.EXCEP<REDO.SO.ORIGIN.ACCT.NO>
*        Y.CREDIT.ACCT.NO = R.STO.DUP.EXCEP<REDO.SO.LOAN.ACCT.NO>
*        Y.DEBIT.AMOUNT   = R.STO.DUP.EXCEP<REDO.SO.CURRENT.AMOUNT.BAL>
*        Y.VERSION        = R.STO.DUP.EXCEP<REDO.SO.VERSION.NAME>
*        LIST.FT.EXCEP<-1> = STO.ID:"@":Y.DESCRIPTION:"@":Y.DEBIT.ACCT.NO:"@":Y.CREDIT.ACCT.NO:"@":Y.DEBIT.AMOUNT:"@":Y.VERSION
*
*    END
* END
* REPEAT

RETURN

END
