SUBROUTINE L.APAP.PROCESS.RABBIT.JSON.REQ.OFS(Request)
    $INSERT I_COMMON
    $INSERT I_EQUATE

    IF PUTENV('OFS_SOURCE=TAABS') THEN
        NULL
    END
    CALL JF.INITIALISE.CONNECTION
    CALL OFS.BULK.MANAGER(Request, result, '')

    CHANGE ',' TO ',':CHARX(10) IN result
    Request = result

RETURN
END
