SUBROUTINE L.APAP.EPOCH.CONV
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_ENQUIRY.COMMON

    Y.DATETIME =O.DATA
    Y.FECHA.LEIBLE = OCONV(ICONV(Y.DATETIME[1,6],"D2/"),'D4Y'):Y.DATETIME[3,4]
    O.DATA = Y.FECHA.LEIBLE

RETURN
END
