SUBROUTINE L.APAP.VAL.ACC.CATEGORY
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.ACCOUNT
    FN.AC = "F.ACCOUNT"
    F.AC = ""
    VarAC = COMI
*DEBUG
    CALL F.READ(FN.AC, VarAC, R.AC, F.AC, '')
    VarCategory = R.AC<AC.CATEGORY>
    IF (VarCategory[1,2] EQ "66" OR VarCategory[1,1] EQ "3") THEN
*DEBUG
        TEXT = "CUENTA INVALIDA"
        CALL DISPLAY.MESSAGE(TEXT, '')
        ETEXT = TEXT
        PRINT E
        CALL STORE.END.ERROR
    END
RETURN
END
