*-----------------------------------------------------------------------------
* <Rating>-30</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE L.APAP.COMPRA.PAS.ACT.LOAD
    $INSERT T24.BP I_COMMON
    $INSERT T24.BP I_EQUATE
    $INSERT T24.BP I_F.ACCOUNT
    $INSERT T24.BP I_F.AZ.ACCOUNT
    $INSERT T24.BP I_F.CUSTOMER
    $INSERT LAPAP.BP L.APAP.COMPRA.PAS.ACT.COMMON
    $INSERT T24.BP I_F.ACCR.ACCT.CR
    $INSERT T24.BP I_F.DATES
    $INSERT T24.BP I_F.EB.CONTRACT.BALANCES
    $INSERT T24.BP I_F.BASIC.INTEREST
    $INSERT T24.BP I_F.ACCOUNT.CREDIT.INT
    $INSERT T24.BP I_F.GROUP.CREDIT.INT

    GOSUB GET.LOARD.TABLE
    GOSUB GET.CONTANTES.VAR
    GOSUB GET.CAMPOS.LOCALES
GET.LOARD.TABLE:
****************
    FN.AZ = "F.AZ.ACCOUNT"
    FV.AZ = ""
    CALL OPF(FN.AZ,FV.AZ)

    FN.AC = "F.ACCOUNT"
    FV.AC = ""
    CALL OPF(FN.AC,FV.AC)

    FN.ACCOUNT = 'F.ACCOUNT' ; F.ACCOUNT = ''
    CALL OPF(FN.ACCOUNT,F.ACCOUNT)

    FN.ACCOUNT.HST = 'F.ACCOUNT$HIS'
    F.ACCOUNT.HST = ''
    CALL OPF(FN.ACCOUNT.HST,F.ACCOUNT.HST)

    FN.CUS = "F.CUSTOMER"
    FV.CUS = ""
    CALL OPF(FN.CUS,FV.CUS)

    FN.RECRF = "F.RE.CRF.MBGL.ALL"
    FV.RECRF = ""
    CALL OPF(FN.RECRF,FV.RECRF)

    FN.INSTIT.FINANC.PARAM = 'F.REDO.APAP.INSTIT.FINANC.PARAM'
    FV.INSTIT.FINANC.PARAM = ''
    CALL OPF(FN.INSTIT.FINANC.PARAM,FV.INSTIT.FINANC.PARAM)

    FN.ACCR.ACCT.CR = 'F.ACCR.ACCT.CR'
    FV.ACCR.ACCT.CR = ''
    CALL OPF(FN.ACCR.ACCT.CR,FV.ACCR.ACCT.CR)

    FN.DATES = 'F.DATES'
    FV.DATES = ''
    CALL OPF(FN.DATES,FV.DATES)

    FN.EBCONTRACT = 'F.EB.CONTRACT.BALANCES'
    F.EBCONTRACT = ''
    CALL OPF(FN.EBCONTRACT,F.EBCONTRACT)

    FN.BINT = "F.BASIC.INTEREST"
    F.BINT = ''
    CALL OPF(FN.BINT,F.BINT)

    FN.ACI = "F.ACCOUNT.CREDIT.INT"
    F.ACI = ''
    CALL OPF(FN.ACI,F.ACI)

    FN.GCI = "F.GROUP.CREDIT.INT"
    F.GCI = ''
    CALL OPF(FN.GCI,F.GCI)
    RETURN

GET.CONTANTES.VAR:
*******************
    VALIDAR.STATUS = "5003":FM:"3005":FM:"3003":FM:"3002":FM:"3004":FM:"3102":FM:"3110"
    ID.BANCO.BHD.LEON.SA = '416673'
    ID.BANCO.BHD = '416191'
    RETURN
GET.CAMPOS.LOCALES:
*******************
    Y.APP = ''; Y.FLD = ''; Y.POS = ''
    Y.APP = 'ACCOUNT'
    Y.FLD = 'L.AC.REINVESTED'
    CALL MULTI.GET.LOC.REF(Y.APP,Y.FLD,Y.POS)
    L.AC.REINVESTED.POS = Y.POS<1,1>
    RETURN
END
