SUBROUTINE L.APAP.TD.OFU

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_ENQUIRY.COMMON
    $INSERT I_F.LATAM.CARD.ORDER

    FN.LATAM = "F.LATAM.CARD.ORDER"
    F.LATAM = ""
    CALL OPF(FN.LATAM,F.LATAM)

    CALL F.READ(FN.LATAM,CARD.ID,R.LATAM,F.LATAM,LATAM.ERR)

    VALID = COMI

    COMI =  VALID[1,6] : 'XXXXXX' : VALID[13,4]

END
