SUBROUTINE LAPAP.MON.ACC.AZ.CLOSURE

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.ACCOUNT
    $INSERT I_F.AZ.ACCOUNT
    $INSERT I_F.ACCOUNT.CLOSURE


    GOSUB INIT
    GOSUB PROCESS

INIT:
*----

    ACC = COMI

    FN.AZ = "F.AZ.ACCOUNT$HIS"
    F.AZ  = ""
    CALL OPF(FN.AZ,F.AZ)

    FN.CLOS = "F.ACCOUNT.CLOSURE"
    F.CLOS = ""
    CALL OPF(FN.CLOS,F.CLOS)

    FN.ACC = "F.ACCOUNT$HIS"
    F.ACC = ""
    CALL OPF(FN.ACC,F.ACC)

    CALL F.READ.HISTORY(FN.ACC,ACC,R.ACC,F.ACC,ERR);
    CALL GET.LOC.REF("ACCOUNT","L.AC.AZ.ACC.REF",POS);
    AZ.ACC.REF = R.ACC<AC.LOCAL.REF,POS>
    CATEGORY = R.ACC<AC.CATEGORY>

    IF CATEGORY GE 6010 AND CATEGORY LE 6020 THEN
        ACC = AZ.ACC.REF
    END ELSE
        ACC = ACC[1,10]
    END

RETURN

PROCESS:
*-------

    CALL F.READ.HISTORY(FN.AZ,ACC,R.AZ,F.AZ,ERRZ)
    INTEREST.LIQU.ACC = R.AZ<AZ.INTEREST.LIQU.ACCT>
    CALL GET.LOC.REF("AZ.ACCOUNT","L.TYPE.INT.PAY",POS)
    L.TYPE.INT.PAY = R.AZ<AZ.LOCAL.REF,POS>

    IF L.TYPE.INT.PAY EQ "Reinvested" THEN

        CALL F.READ(FN.CLOS,INTEREST.LIQU.ACC,R.CLOS,F.CLOS,R.CLOS)
        SETTLEMENT.ACCT = R.CLOS<AC.ACL.SETTLEMENT.ACCT>

        IF SETTLEMENT.ACCT EQ "DOP1403400010017" THEN
            COMI = "EFECTIVO"
        END ELSE
            COMI = "DEPOSITO A TERCERO"
        END

    END

    IF L.TYPE.INT.PAY EQ "Credit.To.Account" THEN

        IF INTEREST.LIQU.ACC EQ "DOP1403200170017" THEN
            COMI = "EFECTIVO"
        END ELSE
            COMI = "DEPOSITO A TERCERO"
        END

    END

    IF ERRZ THEN
        ACC = ACC[1,10]
        CALL F.READ(FN.CLOS,ACC,R.CLOS,F.CLOS,R.CLOS)
        SETTLEMENT.ACCT = R.CLOS<AC.ACL.SETTLEMENT.ACCT>

        IF SETTLEMENT.ACCT EQ "DOP1403400010017" THEN
            COMI = "EFECTIVO"
        END ELSE
            COMI = "DEPOSITO A TERCERO"
        END

    END

RETURN

END
