*-----------------------------------------------------------------------------
* <Rating>68</Rating>
*-----------------------------------------------------------------------------
    SUBROUTINE LAPAP.CHARGE.PAYOFF.SEG.RT(AA.ID,OUT.RECORD1)
    $INSERT T24.BP I_COMMON
    $INSERT T24.BP I_EQUATE
    $INSERT T24.BP I_F.AA.ARRANGEMENT
    $INCLUDE T24.BP I_AA.LOCAL.COMMON
    $INSERT T24.BP I_F.AA.ARRANGEMENT.ACTIVITY
    $INSERT T24.BP I_F.AA.ACTIVITY.CHARGES
    $INSERT T24.BP I_F.ACCT.ACTIVITY
    $INSERT T24.BP I_F.AA.CHARGE
    $INSERT T24.BP I_F.AA.PAYMENT.SCHEDULE
    $INSERT T24.BP I_F.EB.CONTRACT.BALANCES
    $INCLUDE BP I_F.LAPAP.CARGO.EXTRAC
    $INCLUDE BP I_F.LAPAP.CARGO.EXT.SECT
    $INSERT T24.BP I_F.AA.TERM.AMOUNT
    $INSERT T24.BP I_F.CUSTOMER
    $INSERT T24.BP I_F.DATES

    GOSUB MAIN.PROCES
    RETURN
MAIN.PROCES:
    GOSUB LOAD.APLICATIONS
    Y.AA.ID = AA.ID
    Y.TODAY = TODAY
    GOSUB GET.TIEMPO.TRANSCURRIDO
    GOSUB GET.CAPITAL.PENDIENTE
    GOSUB READ.AA.ARRANGEMENT
    Y.DIAS = 'C'
    CALL CDD('',Y.START.DATE, Y.TODAY, Y.DIAS)
    GOSUB VALIDATE.SEGMENTO
    GOSUB SEGMENTO.PROCESS
    RETURN
GET.TIEMPO.TRANSCURRIDO:
    PROP.CLASS = 'TERM.AMOUNT';    PROP.NAME  = ''; returnConditions = ''; RET.ERR = ''
    CALL AA.GET.ARRANGEMENT.CONDITIONS(Y.AA.ID,PROP.CLASS,PROP.NAME,'','',returnConditions,ERR.COND)
    R.AA.TERM.AMOUNT = RAISE(returnConditions)
    Y.TIEMPO.PRESTAMO =  R.AA.TERM.AMOUNT<AA.AMT.TERM>
    BEGIN CASE
    CASE (INDEX(Y.TIEMPO.PRESTAMO,'D',1)GT 0 )
        Y.TIEMPO.PRESTAMO = CHANGE(Y.TIEMPO.PRESTAMO,'D',FM)
        Y.TIEMPO.PRESTAMO = Y.TIEMPO.PRESTAMO<1>
    CASE (INDEX(Y.TIEMPO.PRESTAMO,'M',1)GT 0 )
        Y.TIEMPO.PRESTAMO = CHANGE(Y.TIEMPO.PRESTAMO,'M',FM)
        Y.DIAS.DIFF = DIV(365,12)
        Y.TIEMPO.PRESTAMO = Y.TIEMPO.PRESTAMO<1> * Y.DIAS.DIFF
    CASE (INDEX(Y.TIEMPO.PRESTAMO,'Y',1)GT 0 )
        Y.TIEMPO.PRESTAMO = CHANGE(Y.TIEMPO.PRESTAMO,'Y',FM)
        Y.TIEMPO.PRESTAMO = Y.TIEMPO.PRESTAMO<1> * 365
    END CASE
    RETURN
READ.AA.ARRANGEMENT:
    R.AA.ARRANGEMENT = ''; ERR.AA.ARRANGEMENT = ''
    CALL F.READ (FN.AA.ARRANGEMENT,Y.AA.ID,R.AA.ARRANGEMENT,F.AA.ARRANGEMENT,ERR.AA.ARRANGEMENT)
    Y.START.DATE =  R.AA.ARRANGEMENT<AA.ARR.START.DATE>
    Y.PRODUCT = R.AA.ARRANGEMENT<AA.ARR.PRODUCT>
    Y.CUSTOMER.ID = R.AA.ARRANGEMENT<AA.ARR.CUSTOMER>
    RETURN
LOAD.APLICATIONS:
    FN.AA.ARRANGEMENT = 'F.AA.ARRANGEMENT' ; F.AA.ARRANGEMENT = ''
    CALL OPF (FN.AA.ARRANGEMENT,F.AA.ARRANGEMENT)
    FN.LAPAP.CARGO.EXTRAC = 'F.ST.LAPAP.CARGO.EXTRAC' ; F.LAPAP.CARGO.EXTRAC = ''
    CALL OPF (FN.LAPAP.CARGO.EXTRAC,F.LAPAP.CARGO.EXTRAC)

    FN.CUSTOMER = 'F.CUSTOMER'; F.CUSTOMER = ''
    CALL OPF (FN.CUSTOMER,F.CUSTOMER)

*----------------Tabla con parametrizacion por segmentos-------------------------------
    FN.LAPAP.CARGO.EXT.SECT = 'F.ST.LAPAP.CARGO.EXT.SECT' ; F.LAPAP.CARGO.EXT.SECT = ''
    CALL OPF (FN.LAPAP.CARGO.EXT.SECT,F.LAPAP.CARGO.EXT.SECT)
*--------------------------------------------------------------------------------------
    RETURN
GET.CAPITAL.PENDIENTE:
    CALL L.APAP.RETURN.BANLACE.CANCELACION(Y.AA.ID,OUT.RECORD)
    Y.CAPITAL.PENDIENTE = FIELD(OUT.RECORD,"*",2)
    RETURN

VALIDATE.SEGMENTO:

    Y.APLICA.SEGMENTO       = "TRUE"
    R.CUSTOMER =''; CUSTOMER.ERR ='';
    CALL F.READ(FN.CUSTOMER,Y.CUSTOMER.ID,R.CUSTOMER,F.CUSTOMER,CUSTOMER.ERR)
    CUS.SEG.POS= '';
    CALL GET.LOC.REF("CUSTOMER","L.CU.SEGMENTO",CUS.SEG.POS)
    Y.SEGMENTO              = R.CUSTOMER<EB.CUS.LOCAL.REF,CUS.SEG.POS>
*----------------Busca si el segmento esta parametrizado-------------------------------
    Y.SEGMENTO.ID           = Y.SEGMENTO
    R.CHARGE.PARAM =''; CHARGE.PARAM.ERR = ''
    CALL F.READ(FN.LAPAP.CARGO.EXT.SECT,Y.SEGMENTO.ID,R.CHARGE.PARAM,F.LAPAP.CARGO.EXT.SECT,CHARGE.PARAM.ERR)
    IF NOT (R.CHARGE.PARAM) THEN
    END
    RETURN
SEGMENTO.PROCESS:
    Y.PROD.SEG = R.CHARGE.PARAM<ST.LAP14.PRODUCTO>
    Y.COMIS.SEG = R.CHARGE.PARAM<ST.LAP14.COMISION>
    Y.BASE.CAL.SEG = R.CHARGE.PARAM<ST.LAP14.BASE.CALCULO>
    Y.TIEMPO.TRAN.INI.SEG = R.CHARGE.PARAM<ST.LAP14.TIEMPO.TRAN.INI>
    Y.TIEMPO.TRAN.FIN.SEG = R.CHARGE.PARAM<ST.LAP14.TIEMPO.TRAN.FIN>
    Y.SALDO.BASE.SEG = R.CHARGE.PARAM<ST.LAP14.SALDO.BASE>
    Y.TASA.PORENCIMA.SEG = R.CHARGE.PARAM<ST.LAP14.TASA.PORENCIMA>
    Y.PLAZO.PRESTAMO.SEG = R.CHARGE.PARAM<ST.LAP14.PLAZO.PRESTAMO>
    Y.START.DATE.IN = R.CHARGE.PARAM<ST.LAP14.START.DATE>
    Y.PLAZO.PRESTAMO.SEG                = CHANGE(Y.PLAZO.PRESTAMO.SEG,SM,FM)
    Y.PLAZO.PRESTAMO.SEG                = CHANGE(Y.PLAZO.PRESTAMO.SEG,VM,FM)

    LOCATE Y.PRODUCT IN Y.PROD.SEG<1,1> SETTING PR.POSN.2 THEN
        Y.PLAZO.PRESTAMO.SEG = Y.PLAZO.PRESTAMO.SEG<PR.POSN.2,1> * 365
    END

    IF DROUND(Y.TIEMPO.PRESTAMO) GT DROUND(Y.PLAZO.PRESTAMO.SEG) THEN
        Y.CNT = DCOUNT(Y.PROD.SEG,VM)
        FOR I = 1 TO Y.CNT
            IF Y.PRODUCT EQ Y.PROD.SEG<1,I> THEN
                IF Y.COMIS.SEG<1,I> EQ 'CANCEL.ANTI' THEN
                    Y.FECHA.INC = Y.TIEMPO.TRAN.INI.SEG<1,I>
                    Y.FECHA.FIN = Y.TIEMPO.TRAN.FIN.SEG<1,I>
                    Y.SALDO.BASE1 =  Y.SALDO.BASE.SEG<1,I>
                    Y.TASA.PORENCIMA1 = Y.TASA.PORENCIMA.SEG<1,I>
                    Y.START.DATE.PARAM = Y.START.DATE.IN<1,I>
                    IF Y.START.DATE GE Y.START.DATE.PARAM THEN
                        GOSUB GET.PROCESS.CAL
                    END
                    IF Y.RESUL NE 0 THEN
                        RETURN
                    END
                END
            END
        NEXT I
    END
    RETURN
GET.PROCESS.CAL:
    Y.RESUL = 0; Y.TASA = 0; Y.FECHA = ''
    CHANGE SM TO FM IN Y.FECHA.INC
    CHANGE VM TO FM IN Y.FECHA.INC
    CHANGE SM TO FM IN Y.FECHA.FIN
    CHANGE SM TO FM IN Y.FECHA.FIN
    CHANGE SM TO FM IN Y.TASA.PORENCIMA1
    CHANGE VM TO FM IN Y.TASA.PORENCIMA1
    CHANGE SM TO FM IN Y.SALDO.BASE1
    CHANGE VM TO FM IN Y.SALDO.BASE1

    Y.CNT1 = DCOUNT(Y.FECHA.INC,FM)
    FOR K = 1 TO Y.CNT1
        Y.BALANCE.IN = Y.FECHA.INC<K> * DIV(365,12)
        Y.BALANCE.FIN = Y.FECHA.FIN<K> * DIV(365,12)
        Y.BALANCE.IN = DROUND(Y.BALANCE.IN)
        Y.BALANCE.FIN = DROUND(Y.BALANCE.FIN)
        IF Y.DIAS GE Y.BALANCE.IN AND Y.DIAS LE Y.BALANCE.FIN THEN
            Y.TASA =  DIV(Y.TASA.PORENCIMA1<K>,100)
            Y.PORCIENTO.CAPITAL = DIV(Y.SALDO.BASE1<K>,100) * Y.CAPITAL.PENDIENTE

            Y.RESUL = Y.PORCIENTO.CAPITAL * Y.TASA
            OUT.RECORD1 = Y.RESUL
            RETURN
        END
    NEXT K
    RETURN
END
