SUBROUTINE LAPAP.MON.AZ.GET.PROMOTOR.HIS
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.ACCOUNT


    FN.ACC = "F.ACCOUNT$HIS"
    F.ACC = ""
    CALL OPF(FN.ACC,F.ACC)

    ACC = COMI
    CALL LAPAP.VERIFY.ACC(ACC,RES)
    Y.ACC.ID = RES

    CALL F.READ.HISTORY(FN.ACC,ACC,R.HIS,F.ACC,ERRH)
    PROMOTOR = R.HIS<AC.ACCOUNT.OFFICER>

    COMI = PROMOTOR

RETURN

END
