SUBROUTINE LAPAP.RM.PRD.LIST.OTHER.PRODUCTS

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.DATES
    $INSERT I_F.CR.OTHER.PRODUCTS
    $INSERT I_F.REDO.CUST.PRD.LIST

    FN.PRD = "F.REDO.CUST.PRD.LIST"
    F.PRD = ""
    CALL OPF(FN.PRD,F.PRD)

    FN.OTHER = "F.CR.OTHER.PRODUCTS"
    F.OTHER = ""
    CALL OPF(FN.OTHER,F.OTHER)

    CUSTOMER = R.NEW(CR.OP.CUSTOMER) ;* 10000013 ;* 1000245
    PRODUCT.ID = ID.NEW

    CALL F.READ(FN.PRD,CUSTOMER,R.PRD,F.PRD,ERR.PRD)
    UU = R.PRD<PRD.PRODUCT.ID>

*-----------------------------------
*This function accept S,R,I,A etc...
*-----------------------------------
    IF V$FUNCTION EQ 'R' THEN

        M.VAR = DCOUNT(UU,@VM)
        FOR A = 1 TO M.VAR STEP 1
            IF R.PRD<PRD.PRODUCT.ID,A> EQ PRODUCT.ID  THEN

                R.PRD<PRD.PRD.STATUS,A> = "CLOSED"
                CALL F.WRITE(FN.PRD,CUSTOMER,R.PRD)
*               CALL JOURNAL.UPDATE('')

            END
        NEXT A

    END



END
