SUBROUTINE REDO.E.BLD.VAL.SEL(ENQ.DATA)
    $INSERT I_EQUATE
    $INSERT I_COMMON
    $INSERT I_ENQUIRY.COMMON

    IF NOT(ENQ.DATA<4>) THEN
        ENQ.ERROR = 'EB-SEL.MAND'
        CALL STORE.END.ERROR
        GOSUB END1
    END
RETURN
END1:
END
