SUBROUTINE REDO.B.M.PROP.NONRES.SELECT

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.REDO.H.REPORTS.PARAM
    $INSERT I_REDO.B.M.PROP.NONRES.COMMON
*
    GOSUB PROCESS.PARA
*
RETURN
*
PROCESS.PARA:
*------------
    SEL.CMD = ''
    Y.CUST.IDS = ''
    NO.REC = ''
    SEL.CMD = 'SELECT ':FN.CUSTOMER:' WITH RESIDENCE NE ':FL.PARAM.RES.NE
    CALL EB.READLIST(SEL.CMD,Y.CUST.IDS,'',NO.REC,'')
    CALL BATCH.BUILD.LIST('',Y.CUST.IDS)
*
RETURN
END
