* @ValidationCode : MjotNzUyMjMzOTMzOkNwMTI1MjoxNjgwNzkwMTA5NjIzOklUU1M6LTE6LTE6MjQxMToxOmZhbHNlOk4vQTpSMjFfQU1SLjA6LTE6LTE=
* @ValidationInfo : Timestamp         : 06 Apr 2023 19:38:29
* @ValidationInfo : Encoding          : Cp1252
* @ValidationInfo : User Name         : ITSS
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : 2411
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : true
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R21_AMR.0
* @ValidationInfo : Copyright Temenos Headquarters SA 1993-2021. All rights reserved.
$PACKAGE APAP.REDOBATCH
SUBROUTINE REDO.B.LY.PGEN.TBM.LOAD
*-------------------------------------------------------------------------------------------------
*DESCRIPTION:
* This routine initialises and retrieves data for the local common variable
* This routine is the load routine of the batch job REDO.B.LY.PGEN.TBM which updates
* REDO.LY.POINTS table based on the data defined in the parameter table
* REDO.LY.MODALITY & REDO.LY.PROGRAM
* ------------------------------------------------------------------------------------------------
* Input/Output:
*--------------
* IN : -NA-
* OUT : -NA-
*
* Dependencies:
*---------------
* CALLS : -NA-

* CALLED BY : -NA-
*
* Revision History:
*------------------
* Date who Reference Description
* 06-SEP-2013 RMONDRAGON ODR-2011-06-0243 First Version
*-----------------------------------------------------------------------------
*MODIFICATION HISTORY:
*
* DATE              WHO                REFERENCE                 DESCRIPTION
* 04-APR-2023     Conversion tool    R22 Auto conversion       No changes
* 04-APR-2023      Harishvikram C   Manual R22 conversion      No changes
*------------------------------------------------------------------------------------------------------

    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.DATES

    $INSERT I_REDO.B.LY.PGEN.TBM.COMMON

    GOSUB INIT
    GOSUB OPEN.FILES
    GOSUB OPEN.FILES2
    GOSUB GET.VAL

RETURN

*----
INIT:
*----

    PRG.MOD.LST = '' ; PRG.PER.MOD = '';
    PRG.LST = '' ; PRG.ST.DATE.LST = '';
    PRG.END.DATE.LST = '' ; PRG.DAYS.EXP.LST = '';
    PRG.EXP.DATE.LST = '' ; PRG.CUS.GRP.LST = '';
    PRG.POINT.VALUE.LST = '' ; PRG.AVAIL.IF.DELAY.LST = '';
    PRG.POINT.USE.LST = '' ; PRG.PTS.IN.MOD = '';
    PRG.MINGEN.IN.MOD = '' ; PRG.MAXGEN.IN.MOD = '';
    PRG.FORM.GEN.IN.MOD = '' ; PRG.GEN.AMT.IN.MOD = '';
    PRG.AIR.LST = ''

    G.DATE = ''
    I.DATE = DATE()
    CALL DIETER.DATE(G.DATE,I.DATE,'')

    CUR.DAY = TODAY[7,2]
    CUR.MONTH = TODAY[5,2]
    CUR.YEAR = TODAY[1,4]

    LOC.REF.POS = ''
    LOC.REF.APP = 'CUSTOMER'
    LOC.REF.FIELD = 'L.CU.G.LEALTAD'
    CALL GET.LOC.REF(LOC.REF.APP,LOC.REF.FIELD,LOC.REF.POS)

    POS.L.CU.G.LEALTAD = LOC.REF.POS<1,1>

RETURN

*----------
OPEN.FILES:
*----------

    FN.CUSTOMER = 'F.CUSTOMER'
    F.CUSTOMER = ''
    CALL OPF(FN.CUSTOMER,F.CUSTOMER)

    FN.ACCOUNT = 'F.ACCOUNT'
    F.ACCOUNT = ''
    CALL OPF(FN.ACCOUNT,F.ACCOUNT)

    FN.REDO.LY.POINTS = 'F.REDO.LY.POINTS'
    F.REDO.LY.POINTS = ''
    CALL OPF(FN.REDO.LY.POINTS,F.REDO.LY.POINTS)

    FN.REDO.LY.POINTS.TOT = 'F.REDO.LY.POINTS.TOT'
    F.REDO.LY.POINTS.TOT = ''
    CALL OPF(FN.REDO.LY.POINTS.TOT,F.REDO.LY.POINTS.TOT)

    FN.REDO.LY.MASTERPRGDR = 'F.REDO.LY.MASTERPRGDR'
    F.REDO.LY.MASTERPRGDR = ''
    CALL OPF(FN.REDO.LY.MASTERPRGDR,F.REDO.LY.MASTERPRGDR)

RETURN

*-----------
OPEN.FILES2:
*-----------

    FN.REDO.LY.TXN.BY.MOD = 'F.REDO.LY.TXN.BY.MOD'
    F.REDO.LY.TXN.BY.MOD = ''

* OPEN FN.REDO.LY.TXN.BY.MOD TO F.REDO.LY.TXN.BY.MOD THEN NULL ;*Tus Start
    F.REDO.LY.TXN.BY.MOD = ''
    CALL OPF(FN.REDO.LY.TXN.BY.MOD,F.REDO.LY.TXN.BY.MOD) ;*Tus End

    FN.TEMP.LY.PGEN.TBM = 'F.TEMP.LY.PGEN.TBM'
    F.TEMP.LY.PGEN.TBM = ''
    OPEN FN.TEMP.LY.PGEN.TBM TO F.TEMP.LY.PGEN.TBM ELSE

        TEXT = 'Error in opening : ':FN.TEMP.LY.PGEN.TBM
        CALL FATAL.ERROR('REDO.B.LY.PGEN.TBM.LOAD')
    END

RETURN

*-------
GET.VAL:
*-------


* READ PRG.MOD.LST FROM F.TEMP.LY.PGEN.TBM,'MOD' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'MOD',PRG.MOD.LST,F.TEMP.LY.PGEN.TBM,PRG.MOD.LST.ERR)
    IF PRG.MOD.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.PER.MOD FROM F.TEMP.LY.PGEN.TBM,'NOPRG' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'NOPRG',PRG.PER.MOD,F.TEMP.LY.PGEN.TBM,PRG.PER.MOD.ERR)
    IF PRG.PER.MOD.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.LST FROM F.TEMP.LY.PGEN.TBM,'PRG' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'PRG',PRG.LST,F.TEMP.LY.PGEN.TBM,PRG.LST.ERR)
    IF PRG.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.ST.DATE.LST FROM F.TEMP.LY.PGEN.TBM,'ST.DATE' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'ST.DATE',PRG.ST.DATE.LST,F.TEMP.LY.PGEN.TBM,PRG.ST.DATE.LST.ERR)
    IF PRG.ST.DATE.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.END.DATE.LST FROM F.TEMP.LY.PGEN.TBM,'END.DATE' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'END.DATE',PRG.END.DATE.LST,F.TEMP.LY.PGEN.TBM,PRG.END.DATE.LST.ERR)
    IF PRG.END.DATE.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.DAYS.EXP.LST FROM F.TEMP.LY.PGEN.TBM,'DAYS.EXP' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'DAYS.EXP',PRG.DAYS.EXP.LST,F.TEMP.LY.PGEN.TBM,PRG.DAYS.EXP.LST.ERR)
    IF PRG.DAYS.EXP.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.EXP.DATE.LST FROM F.TEMP.LY.PGEN.TBM,'EXP.DATE' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'EXP.DATE',PRG.EXP.DATE.LST,F.TEMP.LY.PGEN.TBM,PRG.EXP.DATE.LST.ERR)
    IF PRG.EXP.DATE.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.CUS.GRP.LST FROM F.TEMP.LY.PGEN.TBM,'CUS.GROUP' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'CUS.GROUP',PRG.CUS.GRP.LST,F.TEMP.LY.PGEN.TBM,PRG.CUS.GRP.LST.ERR)
    IF PRG.CUS.GRP.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.POINT.VALUE.LST FROM F.TEMP.LY.PGEN.TBM,'POINT.VALUE' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'POINT.VALUE',PRG.POINT.VALUE.LST,F.TEMP.LY.PGEN.TBM,PRG.POINT.VALUE.LST.ERR)
    IF PRG.POINT.VALUE.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.AVAIL.IF.DELAY.LST FROM F.TEMP.LY.PGEN.TBM,'AVAIL.IF.DELAY' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'AVAIL.IF.DELAY',PRG.AVAIL.IF.DELAY.LST,F.TEMP.LY.PGEN.TBM,PRG.AVAIL.IF.DELAY.LST.ERR)
    IF PRG.AVAIL.IF.DELAY.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.POINT.USE.LST FROM F.TEMP.LY.PGEN.TBM,'POINT.USE' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'POINT.USE',PRG.POINT.USE.LST,F.TEMP.LY.PGEN.TBM,PRG.POINT.USE.LST.ERR)
    IF PRG.POINT.USE.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.AIR.LST FROM F.TEMP.LY.PGEN.TBM,'AIR' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'AIR',PRG.AIR.LST,F.TEMP.LY.PGEN.TBM,PRG.AIR.LST.ERR)
    IF PRG.AIR.LST.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.PTS.IN.MOD FROM F.TEMP.LY.PGEN.TBM,'PTS.IN.MOD' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'PTS.IN.MOD',PRG.PTS.IN.MOD,F.TEMP.LY.PGEN.TBM,PRG.PTS.IN.MOD.ERR)
    IF PRG.PTS.IN.MOD.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.MINGEN.IN.MOD FROM F.TEMP.LY.PGEN.TBM,'MIN.GEN.IN.MOD' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'MIN.GEN.IN.MOD',PRG.MINGEN.IN.MOD,F.TEMP.LY.PGEN.TBM,PRG.MINGEN.IN.MOD.ERR)
    IF PRG.MINGEN.IN.MOD.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.MAXGEN.IN.MOD FROM F.TEMP.LY.PGEN.TBM,'MAX.GEN.IN.MOD' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'MAX.GEN.IN.MOD',PRG.MAXGEN.IN.MOD,F.TEMP.LY.PGEN.TBM,PRG.MAXGEN.IN.MOD.ERR)
    IF PRG.MAXGEN.IN.MOD.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.FORM.GEN.IN.MOD FROM F.TEMP.LY.PGEN.TBM,'FORM.GEN.IN.MOD' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'FORM.GEN.IN.MOD',PRG.FORM.GEN.IN.MOD,F.TEMP.LY.PGEN.TBM,PRG.FORM.GEN.IN.MOD.ERR)
    IF PRG.FORM.GEN.IN.MOD.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END


* READ PRG.GEN.AMT.IN.MOD FROM F.TEMP.LY.PGEN.TBM,'GEN.AMT.IN.MOD' ELSE ;*Tus Start
    CALL F.READ(FN.TEMP.LY.PGEN.TBM,'GEN.AMT.IN.MOD',PRG.GEN.AMT.IN.MOD,F.TEMP.LY.PGEN.TBM,PRG.GEN.AMT.IN.MOD.ERR)
    IF PRG.GEN.AMT.IN.MOD.ERR THEN ;* Tus End
        GOSUB READ.ERROR
    END

RETURN

*----------
READ.ERROR:
*----------

    CRT 'Error to Reading in the Record'

RETURN

END
