* @ValidationCode : MjoxODQyNDMxMTMyOkNwMTI1MjoxNjg0ODM2MDQ5NTA3OklUU1M6LTE6LTE6MzcwMDoxOmZhbHNlOk4vQTpSMjFfQU1SLjA6LTE6LTE=
* @ValidationInfo : Timestamp         : 23 May 2023 15:30:49
* @ValidationInfo : Encoding          : Cp1252
* @ValidationInfo : User Name         : ITSS
* @ValidationInfo : Nb tests success  : N/A
* @ValidationInfo : Nb tests failure  : N/A
* @ValidationInfo : Rating            : 3700
* @ValidationInfo : Coverage          : N/A
* @ValidationInfo : Strict flag       : true
* @ValidationInfo : Bypass GateKeeper : false
* @ValidationInfo : Compiler Version  : R21_AMR.0
* @ValidationInfo : Copyright Temenos Headquarters SA 1993-2021. All rights reserved.
$PACKAGE APAP.REDOAPAP
SUBROUTINE REDO.APAP.NOF.LINK.RPT(Y.OUT.ARRAY)
*--------------------------------------------------------------------------------------------------------
*Company   Name    : ASOCIACION POPULAR DE AHORROS Y PRESTAMOS
*Developed By      : Temenos Application Management
*Program   Name    : REDO.APAP.NOF.LINK.AC.INV.RPT
*-------------------------------------------------------------------------------------
*Modification
* Date                   who                   Reference              
* 06-04-2023         CONVERSTION TOOL     R22 AUTO CONVERSTION FM TO @FM AND VM TO @VM AND ++ TO += 1
* 06-04-2023          ANIL KUMAR B        R22 MANUAL CONVERSTION -NO CHANGES
*--------------------------------------------------------------------------------------
*--------------------------------------------------------------------------------------------------------
*Description  : REDO.APAP.NOF.LINK.RPT is the Nofile Enquiry routine
*This routine is used to build data for Enquiry Display from AZ.ACCOUNT
*Attached to  : Standard Selection For the Enquiry REDO.APAP.NOF.LINK.ACCT.INV.RPT
*In Parameter : N/A
*Out Parameter: Y.FINAL.ARRAY
*--------------------------------------------------------------------------------------------------------
*
*
*
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_ENQUIRY.COMMON
    $INSERT I_F.AZ.ACCOUNT
    $INSERT I_F.ACCOUNT
    $INSERT I_F.CUSTOMER
    $INSERT I_F.RELATION.CUSTOMER
    $INSERT I_F.RELATION
    $INSERT I_F.CATEGORY
    $INSERT I_F.DEPT.ACCT.OFFICER
    $INSERT I_F.AZ.PRODUCT.PARAMETER
    $INSERT I_F.ACCOUNT.CLASS
    $INSERT I_F.EB.LOOKUP
* Tus start
    $INSERT I_F.EB.CONTRACT.BALANCES
* Tus end

    GOSUB OPEN
    GOSUB PROCESS

RETURN
*
*
*****
OPEN:
******
*
*
    FN.AZ.ACCOUNT = "F.AZ.ACCOUNT"
    F.AZ.ACCOUNT = ''
    CALL OPF(FN.AZ.ACCOUNT,F.AZ.ACCOUNT)

    FN.AZ.ACCOUNT$HIS = 'F.AZ.ACCOUNT$HIS'
    F.AZ.ACCOUNT$HIS = ''
    CALL OPF(FN.AZ.ACCOUNT$HIS, F.AZ.ACCOUNT$HIS)

    FN.ACCOUNT = "F.ACCOUNT"
    F.ACCOUNT = ''
    CALL OPF(FN.ACCOUNT,F.ACCOUNT)

    FN.ACCOUNT$HIS = "F.ACCOUNT$HIS"
    F.ACCOUNT$HIS = ''
    CALL OPF(FN.ACCOUNT$HIS,F.ACCOUNT$HIS)

    FN.CUSTOMER = "F.CUSTOMER"
    F.CUSTOMER = ''
    CALL OPF(FN.CUSTOMER,F.CUSTOMER)

    FN.RELATION.CUSTOMER = "F.RELATION.CUSTOMER"
    F.RELATION.CUSTOMER = ''
    CALL OPF(FN.RELATION.CUSTOMER,F.RELATION.CUSTOMER)

    FN.RELATION = "F.RELATION"
    F.REALATION = ''
    CALL OPF(FN.RELATION,F.RELATION)

    FN.AZ.PRODUCT.PARAMETER = 'F.AZ.PRODUCT.PARAMETER'
    F.AZ.PRODUCT.PARAMETER = ''
    CALL OPF(FN.AZ.PRODUCT.PARAMETER,F.AZ.PRODUCT.PARAMETER)

    FN.DEPT.ACCT.OFFICER = "F.DEPT.ACCT.OFFICER"
    F.DEPT.ACCT.OFFICER = ''
    CALL OPF(FN.DEPT.ACCT.OFFICER,F.DEPT.ACCT.OFFICER)

    FN.CATEGORY = "F.CATEGORY"
    F.CATEGORY = ''
    CALL OPF(FN.CATEGORY,F.CATEGORY)

    FN.ACCT.CLASS = 'F.ACCOUNT.CLASS'
    F.ACCT.CLASS = ''
    CALL OPF(FN.ACCT.CLASS,F.ACCT.CLASS)

    FN.CUSTOMER.ACCOUNT = 'F.CUSTOMER.ACCOUNT'
    F.CUSTOMER.ACCOUNT = ''
    CALL OPF(FN.CUSTOMER.ACCOUNT, F.CUSTOMER.ACCOUNT)

    FN.REDO.EMPLOYEE.ACCOUNTS = 'F.REDO.EMPLOYEE.ACCOUNTS'
    F.REDO.EMPLOYEE.ACCOUNTS = ''
    CALL OPF(FN.REDO.EMPLOYEE.ACCOUNTS, F.REDO.EMPLOYEE.ACCOUNTS)

    FN.EB.LOOKUP = 'F.EB.LOOKUP'
    F.EB.LOOKUP = ''
    CALL OPF(FN.EB.LOOKUP , F.EB.LOOKUP)

    FN.AZ.CUSTOMER = 'F.AZ.CUSTOMER'
    F.AZ.CUSTOMER = ''
    CALL OPF(FN.AZ.CUSTOMER, F.AZ.CUSTOMER)

RETURN
*
*
********
PROCESS:
**********
*
*

    LOCATE 'CLIENT.CODE' IN D.FIELDS<1> SETTING Y.CLIENT.CODE.POS THEN
        Y.CLIENT.CODE.SEL = D.RANGE.AND.VALUE<Y.CLIENT.CODE.POS>
    END

    LOCATE 'RELATION.TYPE' IN D.FIELDS<1> SETTING Y.REL.TYPE.POS THEN
        Y.RELATION.TYPE = D.RANGE.AND.VALUE<Y.REL.TYPE.POS>
    END


    IF Y.CLIENT.CODE.SEL NE '' THEN
        R.SEL.LIST = Y.CLIENT.CODE.SEL

        Y.READ.ERR = ''
        R.SEL.EMP.REC = ''
        CALL F.READ(FN.REDO.EMPLOYEE.ACCOUNTS, R.SEL.LIST, R.SEL.EMP.REC, F.REDO.EMPLOYEE.ACCOUNTS, Y.READ.ERR)

        IF NOT(R.SEL.EMP.REC) THEN
            RETURN
        END


    END ELSE
        Y.SEL.CMD = 'SELECT ':FN.REDO.EMPLOYEE.ACCOUNTS
        CALL EB.READLIST(Y.SEL.CMD, R.SEL.LIST, '', '', Y.READ.ERR)
    END

    GOSUB GET.LR.POSITIONS

    LOOP
        REMOVE Y.CLIENT.CODE FROM R.SEL.LIST SETTING Y.CLIENT.CODE.POS
    WHILE Y.CLIENT.CODE:Y.CLIENT.CODE.POS

        Y.LINK.CUSTOMER.ID = Y.CLIENT.CODE
        GOSUB GET.CUSTOMER.DETAILS

    REPEAT

RETURN

*
*
*******************
GET.LR.POSITIONS:
******************
*
*

    APL.ARRAY = 'CUSTOMER':@FM:'ACCOUNT':@FM:'AZ.ACCOUNT'
    APL.FIELD ='L.CU.TIPO.CL':@FM:'L.AC.REINVESTED':@VM:'L.AC.STATUS1':@VM:'L.AC.STATUS2':@FM:'L.AC.STATUS1':@VM:'L.AC.STATUS2':@VM:'L.TYPE.INT.PAY'
    FLD.POS = ''
    CALL MULTI.GET.LOC.REF(APL.ARRAY,APL.FIELD,FLD.POS)
    LOC.L.CU.TIPO.CL.POS = FLD.POS<1,1>
    LOC.L.AC.REINVESTED.POS = FLD.POS<2,1>
    LOC.L.AC.STATUS1.POS = FLD.POS<2,2>
    LOC.L.AC.STATUS2.POS = FLD.POS<2,3>
    L.AZ.STATUS1.POS = FLD.POS<3,1>
    L.AZ.STATUS2.POS  = FLD.POS<3,2>
    L.AZ.TYPE.POS = FLD.POS<3,3>

RETURN

*
*
*********************
GET.CUSTOMER.DETAILS:
*********************
*
*
    CUSTOMER.ERR = ''
    R.CUSTOMER = ''
    CALL F.READ(FN.CUSTOMER,Y.CLIENT.CODE,R.CUSTOMER,F.CUSTOMER,CUSTOMER.ERR)

    Y.L.CU.TIPO.CL = R.CUSTOMER<EB.CUS.LOCAL.REF,LOC.L.CU.TIPO.CL.POS>
    Y.CUSTOMER.CODE = Y.CLIENT.CODE
    IF Y.L.CU.TIPO.CL EQ "PERSONA JURDICIA" THEN
        Y.CUS.CLIENT.NAMES = R.CUSTOMER<EB.CUS.NAME.1>:" ":R.CUSTOMER<EB.CUS.NAME.2>
    END ELSE
        Y.CUS.CLIENT.NAMES = R.CUSTOMER<EB.CUS.GIVEN.NAMES>:" ":R.CUSTOMER<EB.CUS.FAMILY.NAME>
    END

    RELATION.ERR = ''
    R.RELATION.CUSTOMER = ''
    CALL F.READ(FN.RELATION.CUSTOMER,Y.CLIENT.CODE,R.RELATION.CUSTOMER,F.RELATION.CUSTOMER,RELATION.ERR)

    Y.CUS.AC.OFF = R.CUSTOMER<EB.CUS.ACCOUNT.OFFICER>
* Y.REL.CODE = R.CUSTOMER<EB.CUS.RELATION.CODE>
    Y.REL.CODE = R.RELATION.CUSTOMER<EB.RCU.IS.RELATION>
    Y.NO.REL.CODES = DCOUNT(R.RELATION.CUSTOMER<EB.RCU.IS.RELATION>,@VM)
    Y.REL.CUS.ALL.CUS = R.RELATION.CUSTOMER<EB.RCU.OF.CUSTOMER>
    Y.REL.CUS.ALL.LOOP = Y.REL.CUS.ALL.CUS

    Y.REPEATED.CUST = ''
    Y.RPTD.CUS.PROCESS.FLAG = ''
    Y.RPTD.REL.CODE = ''

    Y.LOOP.CNT1 = 1

    Y.REL.CUST.LIST = ''
    Y.REL.LIST.OF.CUS = ''

    LOOP
        REMOVE Y.CUS.REL.VAL FROM Y.REL.CUS.ALL.CUS SETTING Y.CUS.REL.POS
    WHILE Y.CUS.REL.VAL:Y.CUS.REL.POS
        IF Y.RELATION.TYPE AND ((Y.RELATION.TYPE) NE (Y.REL.CODE<1, Y.LOOP.CNT1>)) THEN
            Y.LOOP.CNT1 += 1
            CONTINUE
        END
        IF Y.REL.CODE<1, Y.LOOP.CNT1> GE 300 AND Y.REL.CODE<1, Y.LOOP.CNT1> LE 499 THEN
            LOCATE Y.CUS.REL.VAL IN Y.REL.CUST.LIST<1,1> SETTING Y.REL.CUS.LOCATE.POS THEN
                Y.REL.CUST.LIST<1,Y.REL.CUS.LOCATE.POS> = Y.REL.CUS.ALL.CUS<1, Y.LOOP.CNT1>
                Y.REL.LIST.OF.CUS<1, Y.REL.CUS.LOCATE.POS, -1> = Y.REL.CODE<1, Y.LOOP.CNT1>
            END ELSE
                Y.REL.CUST.LIST<1,Y.REL.CUS.LOCATE.POS> = Y.REL.CUS.ALL.CUS<1, Y.LOOP.CNT1>
                Y.REL.LIST.OF.CUS<1, Y.REL.CUS.LOCATE.POS, -1> = Y.REL.CODE<1, Y.LOOP.CNT1>
            END
        END
        Y.LOOP.CNT1 += 1
    REPEAT


    Y.REL.CUST.LIST = INSERT(Y.REL.CUST.LIST, 1,1 ; Y.CLIENT.CODE)
    Y.REL.LIST.OF.CUS = INSERT(Y.REL.LIST.OF.CUS, 1, 1; "")

    Y.FC.LOOP = 1
    LOOP
        REMOVE Y.REP.CLIENT.CODE FROM Y.REL.CUST.LIST SETTING Y.REP.CLIENT.POS
    WHILE Y.REP.CLIENT.CODE:Y.REP.CLIENT.POS

        IF Y.RELATION.TYPE AND (Y.REL.LIST.OF.CUS<1,Y.FC.LOOP> EQ '') THEN
            Y.FC.LOOP += 1
            Y.EMPLOYEE.ID = Y.REP.CLIENT.CODE
            CALL F.READ(FN.CUSTOMER, Y.EMPLOYEE.ID, R.EMP.REC, F.CUSTOMER, Y.READ.ERR)

            Y.L.CU.TIPO.CL = R.EMP.REC<EB.CUS.LOCAL.REF,LOC.L.CU.TIPO.CL.POS>

            IF Y.L.CU.TIPO.CL EQ "PERSONA JURDICIA" THEN
                Y.EMPLOYEE.NAME = R.EMP.REC<EB.CUS.NAME.1>:" ":R.EMP.REC<EB.CUS.NAME.2> ;*
            END ELSE
                Y.EMPLOYEE.NAME = R.EMP.REC<EB.CUS.GIVEN.NAMES>:" ":R.EMP.REC<EB.CUS.FAMILY.NAME> ;*
            END

            CONTINUE
        END

        IF Y.FC.LOOP GT 1 THEN
            Y.READ.ERR = ''
            R.EMPLOYEE.ACCT = ''
            CALL F.READ(FN.REDO.EMPLOYEE.ACCOUNTS, Y.REP.CLIENT.CODE, R.EMPLOYEE.ACCT, F.REDO.EMPLOYEE.ACCOUNTS, Y.READ.ERR)

            IF R.EMPLOYEE.ACCT THEN
                CONTINUE
            END
        END

*       Y.READ.ERR = ''
*       R.AZ.CUSTOMER = ''
*       CALL F.READ(FN.AZ.CUSTOMER, Y.REP.CLIENT.CODE, R.AZ.CUSTOMER, F.AZ.CUSTOMER, Y.READ.ERR)

        Y.READ.ERR = ''
        R.CUS.ACC = ''
        CALL F.READ(FN.CUSTOMER.ACCOUNT, Y.REP.CLIENT.CODE, R.AZ.CUSTOMER, F.CUSTOMER.ACCOUNT, Y.READ.ERR)

        Y.READ.ERR = ''
        R.CUSTOMER = ''
        CALL F.READ(FN.CUSTOMER, Y.REP.CLIENT.CODE, R.CUSTOMER, F.CUSTOMER, Y.READ.ERR)

        GOSUB CHECK.ALL.ACCOUNTS

        Y.FC.LOOP += 1

    REPEAT










* For each relation codes they are reading and storing the description.
* Read this customers CUSTOMER.ACCOUNT and check whwether he has a deposit with the bank.
* After that change the below loop to check the deposits of the relations.

*    Y.INIT.CUST = 1
*   Y.EMPLOYEE.NAME = Y.CUS.CLIENT.NAMES
*
*    IF Y.RELATION.TYPE ELSE
*        GOSUB GET.CURR.CUS.DEP
*    END
*
*    Y.REL.CODE.CT = 1  ; Y.FOUND = ''
*
*    LOOP
*
*        Y.REPEAT.REL.CUST = ''
*
*    WHILE Y.REL.CODE.CT LE Y.NO.REL.CODES AND NOT(Y.FOUND) DO
*    IF R.RELATION.CUSTOMER<EB.RCU.IS.RELATION,Y.REL.CODE.CT> GE 300 AND R.RELATION.CUSTOMER<EB.RCU.IS.RELATION,Y.REL.CODE.CT> LE 499 THEN
*
*        IF Y.RELATION.TYPE AND (Y.RELATION.TYPE GT 300 AND Y.RELATION.TYPE LT 500) THEN
*            IF R.RELATION.CUSTOMER<EB.RCU.IS.RELATION, Y.REL.CODE.CT> EQ Y.RELATION.TYPE THEN
*
*                CALL F.READ(FN.RELATION,R.RELATION.CUSTOMER<1,Y.REL.CODE.CT>,R.RELATION,F.RELATION,RELATE.ERROR)
*                Y.TYPE.OF.REL = R.RELATION<EB.REL.DESCRIPTION>
*                Y.CLIENT.CODE = R.RELATION.CUSTOMER<EB.RCU.OF.CUSTOMER, Y.REL.CODE.CT>
*
*                Y.INIT.CUST = 0
*                GOSUB GET.CURR.CUS.DEP
*
*            END
*            ELSE
*                Y.REL.CODE.CT++
*                CONTINUE
*            END
*        END ELSE
*
*            Y.CLIENT.CODE = R.RELATION.CUSTOMER<EB.RCU.OF.CUSTOMER, Y.REL.CODE.CT>
*            CALL F.READ(FN.RELATION,R.RELATION.CUSTOMER<1,Y.REL.CODE.CT>,R.RELATION,F.RELATION,RELATE.ERROR)
*            Y.TYPE.OF.REL = R.RELATION<EB.REL.DESCRIPTION>
*            Y.INIT.CUST = 0
*
*            IF R.RELATION.CUSTOMER<1,Y.REL.CODE.CT> GT 300 AND R.RELATION.CUSTOMER<1,Y.REL.CODE.CT> LT 500 THEN
*                GOSUB GET.CURR.CUS.DEP
*            END
*
*        END
*        Y.REL.CODE.CT++
*    REPEAT
*    CHANGE FM TO VM IN Y.REL.CODE.DESC

RETURN

CHECK.ALL.ACCOUNTS:
*---------------------

    LOOP
        REMOVE Y.AZ.ID FROM R.AZ.CUSTOMER SETTING Y.AZ.ID.POS
    WHILE Y.AZ.ID:Y.AZ.ID.POS

        Y.READ.ERR = ''
        R.ACCOUNT = ''
        CALL F.READ(FN.ACCOUNT, Y.AZ.ID, R.ACCOUNT, F.ACCOUNT, Y.READ.ERR)
*   Tus Start
        R.ECB = ''
        ECB.ERR = ''
        CALL EB.READ.HVT("EB.CONTRACT.BALANCES", Y.AZ.ID, R.ECB, ECB.ERR) ; * Tus End

        Y.READ.ERR = ''
        R.AZ.RECORD = ''
        CALL F.READ(FN.AZ.ACCOUNT, Y.AZ.ID, R.AZ.RECORD, F.AZ.ACCOUNT, Y.READ.ERR)

        IF NOT(R.AZ.RECORD) THEN
            Y.READ.ERR = ''
            Y.AZ.HIST.ID = Y.AZ.ID:';1'
            CALL F.READ(FN.AZ.ACCOUNT$HIS, Y.AZ.HIST.ID, R.AZ.RECORD, F.AZ.ACCOUNT$HIS, Y.READ.ERR)
        END

        IF R.AZ.RECORD THEN
            GOSUB GET.AC.DETAILS
        END

    REPEAT

RETURN

*************************
GET.AC.WBAL.FOR.LIQ.AC:
*======================
    R.AC.LIQ.REC = ''
    CALL F.READ(FN.ACCOUNT,R.AZ.RECORD<AZ.INTEREST.LIQU.ACCT>,R.AC.LIQ.REC,F.ACCOUNT,Y.ACLIQ.ERR)
*  Tus start
    R.ECB1 = ''
    ECB.ERR1 = ''
    CALL EB.READ.HVT("EB.CONTRACT.BALANCES",R.AZ.RECORD<AZ.INTEREST.LIQU.ACCT>,R.ECB1,ECB.ERR1)

*  RET.BAL = R.AC.LIQ.REC<AC.WORKING.BALANCE>
    RET.BAL = R.ECB1<ECB.WORKING.BALANCE>
*   Tus end

RETURN

***********************
*GET.CURR.CUS.DEP:
*-----------------
*
*    Y.READ.ERR = ''
*    R.CUS.ACC = ''
*    CALL F.READ(FN.CUSTOMER.ACCOUNT, Y.CLIENT.CODE, R.CUS.ACC, F.CUSTOMER.ACCOUNT, Y.READ.ERR)
*
*    Y.READ.ERR = ''
*    R.CUSTOMER = ''
*    CALL F.READ(FN.CUSTOMER, Y.CLIENT.CODE, R.CUSTOMER, F.CUSTOMER, Y.READ.ERR)
*
*
*    LOOP
*        REMOVE Y.AC.ID FROM R.CUS.ACC SETTING Y.AC.ID.POS
*    WHILE Y.AC.ID:Y.AC.ID.POS
*        Y.READ.ERR = ''
*        R.AZ.RECORD = ''
*        CALL F.READ(FN.AZ.ACCOUNT, Y.AC.ID, R.AZ.RECORD, F.AZ.ACCOUNT, Y.READ.ERR)
*
*        IF NOT(R.AZ.RECORD) THEN
*            CALL EB.READ.HISTORY.REC(F.AZ.ACCOUNT$HIS, Y.AC.ID, R.AZ.RECORD, Y.READ.ERR)
*            Y.AC.ID = FIELD(Y.AC.ID, ';', 1)
*        END
*
*        IF R.AZ.RECORD THEN
*
*            GOSUB GET.AC.DETAILS
*        END
*
*    REPEAT
*
*    RETURN
*------------------------------------------
GET.AC.DETAILS:
*--------------

*    Y.READ.ERR = ''
*    R.ACCOUNT = ''
*    CALL F.READ(FN.ACCOUNT, Y.AC.ID, R.ACCOUNT, F.ACCOUNT, Y.READ.ERR)

*    IF NOT(R.ACCOUNT) THEN
**        CALL EB.READ.HISTORY.REC(F.ACCOUNT$HIS, Y.AC.ID, R.ACCOUNT, Y.READ.ERR)
*        Y.AC.ID = FIELD(Y.AC.ID, ';', 1)
*    END


    Y.AC.AGN = R.ACCOUNT<AC.CO.CODE>      ;*
    Y.AC.OFF = R.ACCOUNT<AC.ACCOUNT.OFFICER>        ;*

    R.DAO.REC = ''
    CALL CACHE.READ(FN.DEPT.ACCT.OFFICER,Y.AC.OFF,R.DAO.REC,Y.DAO.ERR)
    Y.AC.OFF.DESC = R.DAO.REC<EB.DAO.NAME>
    Y.REGION = Y.CUS.AC.OFF[LEN(Y.CUS.AC.OFF)-7,2]  ;*
    Y.CLIENT.ID =  Y.REP.CLIENT.CODE      ;*

    Y.L.CU.TIPO.CL = R.CUSTOMER<EB.CUS.LOCAL.REF,LOC.L.CU.TIPO.CL.POS>
    Y.CUSTOMER.CODE = Y.CLIENT.CODE
    IF Y.L.CU.TIPO.CL EQ "PERSONA JURDICIA" THEN
        Y.CUS.CLIENT.NAMES = R.CUSTOMER<EB.CUS.NAME.1>:" ":R.CUSTOMER<EB.CUS.NAME.2>
    END ELSE
        Y.CUS.CLIENT.NAMES = R.CUSTOMER<EB.CUS.GIVEN.NAMES>:" ":R.CUSTOMER<EB.CUS.FAMILY.NAME>
    END


    IF Y.FC.LOOP EQ 1 THEN
        Y.TYPE.OF.REL = ''
        Y.EMPLOYEE.ID = Y.REL.CUST.LIST<1,1>
        Y.EMPLOYEE.NAME = Y.CUS.CLIENT.NAMES
    END
*
    Y.TYPE.OF.CLIENT = Y.L.CU.TIPO.CL     ;*

    Y.TYPE.OF.DEPOSIT = R.AZ.RECORD<AZ.CATEGORY>

    Y.READ.ERR = ''
    R.CATEGORY = ''
    CALL CACHE.READ(FN.CATEGORY, Y.TYPE.OF.DEPOSIT, R.CATEGORY, Y.READ.ERR)

    Y.TYPE.OF.DEPOSIT = R.CATEGORY<EB.CAT.DESCRIPTION, LNGG>

    IF NOT(Y.TYPE.OF.DEPOSIT) THEN
        Y.TYPE.OF.DEPOSIT = R.CATEGORY<EB.CAT.DESCRIPTION, 1>   ;*
    END

    Y.NUM.OF.DEPOSIT = Y.AZ.ID  ;*
    Y.BENEFICIARY = Y.CUS.CLIENT.NAMES    ;*
    Y.AZ.CCY = R.AZ.RECORD<AZ.CURRENCY>   ;*
    Y.DEPOSIT.AMT = R.AZ.RECORD<AZ.ORIG.PRINCIPAL>  ;*
    RE.INV.DEPOSIT = R.AZ.RECORD<AZ.LOCAL.REF, L.AZ.TYPE.POS>

    IF RE.INV.DEPOSIT EQ 'Reinvested' THEN
        GOSUB GET.AC.WBAL.FOR.LIQ.AC
        Y.CURR.AMT = R.AZ.RECORD<AZ.PRINCIPAL> +  RET.BAL
    END ELSE
        Y.CURR.AMT = R.AZ.RECORD<AZ.PRINCIPAL>
    END

    Y.DEPOSIT.AMT.ACTUAL = Y.CURR.AMT     ;*

    IF R.ACCOUNT<AC.CLOSURE.DATE> THEN
        IF LNGG EQ 2 THEN
            Y.ACC.STATUS = 'CUENTA CERRADA'   ;*
        END ELSE
            Y.ACC.STATUS = 'CLOSED'
        END
    END

    Y.STATUS1 = R.ACCOUNT<AC.LOCAL.REF, LOC.L.AC.STATUS1.POS> ;*
    Y.STATUS2 = R.ACCOUNT<AC.LOCAL.REF, LOC.L.AC.STATUS2.POS> ;*
    Y.AZ.STATUS1 = R.AZ.RECORD<AZ.LOCAL.REF,L.AZ.STATUS1.POS>
    Y.AZ.STATUS2 = R.AZ.RECORD<AZ.LOCAL.REF,L.AZ.STATUS2.POS>

    Y.STATUS1.ID = 'L.AC.STATUS1*':Y.STATUS1
    R.STATUS1.REC = ''
    CALL F.READ(FN.EB.LOOKUP, Y.STATUS1.ID, R.STATUS1.REC, F.EB.LOOKUP, Y.READ.ERR)

    Y.STATUS2.ID = 'L.AC.STATUS2*':Y.STATUS2
    R.STATUS2.REC = ''
    CALL F.READ(FN.EB.LOOKUP, Y.STATUS2.ID, R.STATUS2.REC, F.EB.LOOKUP, Y.READ.ERR)

    Y.AZ.STATUS1.ID = 'L.AC.STATUS1*':Y.AZ.STATUS1
    R.AZ.STATUS1.REC = ''
    CALL F.READ(FN.EB.LOOKUP, Y.AZ.STATUS1.ID, R.AZ.STATUS1.REC, F.EB.LOOKUP, Y.READ.ERR)

    Y.AZ.STATUS2.ID = 'L.AC.STATUS2*':Y.AZ.STATUS2
    R.AZ.STATUS2.REC = ''
    CALL F.READ(FN.EB.LOOKUP, Y.AZ.STATUS2.ID, R.AZ.STATUS2.REC, F.EB.LOOKUP, Y.READ.ERR)

    Y.STATUS1 = R.STATUS1.REC<EB.LU.DESCRIPTION, LNGG>
    Y.STATUS2 = R.STATUS2.REC<EB.LU.DESCRIPTION, LNGG>
    Y.AZ.STATUS1 = R.AZ.STATUS1.REC<EB.LU.DESCRIPTION, LNGG>
    Y.AZ.STATUS2 = R.AZ.STATUS2.REC<EB.LU.DESCRIPTION, LNGG>

    Y.CANCEL.DATE = R.ACCOUNT<AC.CLOSURE.DATE>      ;*

    Y.AC.CATEGORY = R.ACCOUNT<AC.CATEGORY>
    CALL CACHE.READ(FN.CATEGORY, Y.AC.CATEGORY, R.CAT, Y.READ.ERR)
    Y.AC.TYPE = R.CAT<EB.CAT.DESCRIPTION> ;*
    Y.AC.OPEN.DATE = R.ACCOUNT<AC.OPENING.DATE>     ;*
    Y.OPEN.DATE = Y.AC.OPEN.DATE
    Y.ACT.CCY = R.ACCOUNT<AC.CURRENCY>    ;*
*  Tus start
*  Y.AC.ACT.BAL = R.ACCOUNT<AC.ONLINE.ACTUAL.BAL>  ;*
    Y.AC.ACT.BAL = R.ECB<ECB.ONLINE.ACTUAL.BAL>  ;*
*  Tus end
    Y.AC.STATUS = Y.ACC.STATUS  ;*
    Y.AC.CANCEL.DATE = Y.CANCEL.DATE      ;*
    Y.AC.CUS.NAME = R.CUSTOMER<EB.CUS.SHORT.NAME>   ;*

    GOSUB GET.REL.RPTD

    Y.OUT.ARRAY<-1> = Y.AC.AGN:"*":Y.AC.OFF.DESC:"*":Y.REGION:"*":Y.CLIENT.ID:"*":Y.CUS.CLIENT.NAMES:"*":Y.TYPE.OF.REL:"*":Y.TYPE.OF.CLIENT:"*":Y.TYPE.OF.DEPOSIT:"*":Y.NUM.OF.DEPOSIT:"*":Y.BENEFICIARY:"*":Y.OPEN.DATE:"*":Y.AZ.CCY:"*":Y.DEPOSIT.AMT:"*":Y.DEPOSIT.AMT.ACTUAL:"*":Y.ACC.STATUS:"*":Y.AZ.STATUS1:"*":Y.AZ.STATUS2:"*":Y.CANCEL.DATE:"*":Y.AC.TYPE
    Y.OUT.ARRAY := "*":Y.AC.ID:"*":Y.AC.CUS.NAME:"*":Y.AC.OPEN.DATE:"*":Y.ACT.CCY:"*":Y.AC.ACT.BAL:"*":Y.AC.STATUS:"*":Y.STATUS1:"*":Y.STATUS2:"*":Y.AC.CANCEL.DATE:"*":Y.LINK.CUSTOMER.ID:"*":Y.EMPLOYEE.NAME


    Y.AC.AGN = '' ; Y.AC.OFF.DESC = '' ; Y.REGION = ''; Y.CLIENT.ID = '' ;
    Y.CUS.CLIENT.NAMES = ''; Y.TYPE.OF.CLIENT = ''; Y.TYPE.OF.DEPOSIT = '';
    Y.NUM.OF.REPOSIT = '' ; Y.BENEFICIARY = ''; Y.OPEN.DATE = '' ;Y.AZ.CCY = ''; Y.DEPOSIT.AMT = '' ;
    Y.DEPOSIT.AMT.ACTUAL = ''; Y.ACC.STATUS = ''; Y.AZ.STATUS1 = ''; Y.AZ.STATUS2 = '';
    Y.CANCEL.DATE = ''; Y.AC.TYPE = '' ; Y.AC.ID = '' ; Y.AC.CUS.NAME = ''; Y.AC.OPEN.DATE = '';
    Y.ACT.CCY = '' ; Y.AC.ACT.BAL = '' ; Y.AC.STATUS = '' ; Y.STATUS1 = '' ; Y.STATUS2 = '' ; Y.AC.CANCEL.DATE = '';

RETURN

*-------------------------------
GET.REL.RPTD:
*--------------

    LOCATE Y.REP.CLIENT.CODE IN Y.REL.CUST.LIST<1,1> SETTING Y.REL.REP.CUS.POS THEN
        Y.REL.CODES.RPTD = Y.REL.LIST.OF.CUS<1, Y.REL.REP.CUS.POS>
    END

    Y.TYPE.OF.REL = ''
    LOOP
        REMOVE Y.RPTD.REL.COD FROM Y.REL.CODES.RPTD SETTING RPTD.REL.CODE.POS
    WHILE Y.RPTD.REL.COD:RPTD.REL.CODE.POS
        CALL F.READ(FN.RELATION, Y.RPTD.REL.COD, R.RPTD.RELATION, F.RELATION, Y.READ.ERR)
        Y.TYPE.OF.REL1 = R.RPTD.RELATION<EB.REL.DESCRIPTION, LNGG>
        IF Y.TYPE.OF.REL1 ELSE
            Y.TYPE.OF.REL1 = R.RPTD.RELATION<EB.REL.DESCRIPTION, 1>
        END
        Y.TYPE.OF.REL<1,-1> = Y.TYPE.OF.REL1
    REPEAT


RETURN
*-------------------------------

END
*------------End of Program----------------------------------------------------------------------------------------------------------------------------
